run:
  deadline: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - build
    - protobuf
  skip-files:
    - steamlang/steammsg.go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    check-shadowing: true
    use-installed-packages: false
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US
  lll:
    line-length: 120
    tab-width: 1
  unused:
    check-exported: false
  unparam:
    algo: cha
    check-exported: false
  nakedret:
    max-func-lines: 10

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - golint
    - unconvert
    - goimports
    - misspell
    - lll
    - unparam

issues:
  new: false
  max-per-linter: 10
  max-same: 3
  exclude-use-default: true
  exclude:
    - "`\\(\\*GenGo\\)\\.sfield`.+always receives"
