// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_parental.steamclient.proto

package client // import "github.com/13k/go-steam-resources/protobuf/steam/client"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ParentalApp struct {
	Appid                *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	IsAllowed            *bool    `protobuf:"varint,2,opt,name=is_allowed,json=isAllowed" json:"is_allowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentalApp) Reset()         { *m = ParentalApp{} }
func (m *ParentalApp) String() string { return proto.CompactTextString(m) }
func (*ParentalApp) ProtoMessage()    {}
func (*ParentalApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{0}
}
func (m *ParentalApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentalApp.Unmarshal(m, b)
}
func (m *ParentalApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentalApp.Marshal(b, m, deterministic)
}
func (dst *ParentalApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentalApp.Merge(dst, src)
}
func (m *ParentalApp) XXX_Size() int {
	return xxx_messageInfo_ParentalApp.Size(m)
}
func (m *ParentalApp) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentalApp.DiscardUnknown(m)
}

var xxx_messageInfo_ParentalApp proto.InternalMessageInfo

func (m *ParentalApp) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *ParentalApp) GetIsAllowed() bool {
	if m != nil && m.IsAllowed != nil {
		return *m.IsAllowed
	}
	return false
}

type ParentalSettings struct {
	Steamid                *uint64        `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	ApplistBaseId          *uint32        `protobuf:"varint,2,opt,name=applist_base_id,json=applistBaseId" json:"applist_base_id,omitempty"`
	ApplistBaseDescription *string        `protobuf:"bytes,3,opt,name=applist_base_description,json=applistBaseDescription" json:"applist_base_description,omitempty"`
	ApplistBase            []*ParentalApp `protobuf:"bytes,4,rep,name=applist_base,json=applistBase" json:"applist_base,omitempty"`
	ApplistCustom          []*ParentalApp `protobuf:"bytes,5,rep,name=applist_custom,json=applistCustom" json:"applist_custom,omitempty"`
	Passwordhashtype       *uint32        `protobuf:"varint,6,opt,name=passwordhashtype" json:"passwordhashtype,omitempty"`
	Salt                   []byte         `protobuf:"bytes,7,opt,name=salt" json:"salt,omitempty"`
	Passwordhash           []byte         `protobuf:"bytes,8,opt,name=passwordhash" json:"passwordhash,omitempty"`
	IsEnabled              *bool          `protobuf:"varint,9,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
	EnabledFeatures        *uint32        `protobuf:"varint,10,opt,name=enabled_features,json=enabledFeatures" json:"enabled_features,omitempty"`
	RecoveryEmail          *string        `protobuf:"bytes,11,opt,name=recovery_email,json=recoveryEmail" json:"recovery_email,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}       `json:"-"`
	XXX_unrecognized       []byte         `json:"-"`
	XXX_sizecache          int32          `json:"-"`
}

func (m *ParentalSettings) Reset()         { *m = ParentalSettings{} }
func (m *ParentalSettings) String() string { return proto.CompactTextString(m) }
func (*ParentalSettings) ProtoMessage()    {}
func (*ParentalSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{1}
}
func (m *ParentalSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentalSettings.Unmarshal(m, b)
}
func (m *ParentalSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentalSettings.Marshal(b, m, deterministic)
}
func (dst *ParentalSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentalSettings.Merge(dst, src)
}
func (m *ParentalSettings) XXX_Size() int {
	return xxx_messageInfo_ParentalSettings.Size(m)
}
func (m *ParentalSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentalSettings.DiscardUnknown(m)
}

var xxx_messageInfo_ParentalSettings proto.InternalMessageInfo

func (m *ParentalSettings) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *ParentalSettings) GetApplistBaseId() uint32 {
	if m != nil && m.ApplistBaseId != nil {
		return *m.ApplistBaseId
	}
	return 0
}

func (m *ParentalSettings) GetApplistBaseDescription() string {
	if m != nil && m.ApplistBaseDescription != nil {
		return *m.ApplistBaseDescription
	}
	return ""
}

func (m *ParentalSettings) GetApplistBase() []*ParentalApp {
	if m != nil {
		return m.ApplistBase
	}
	return nil
}

func (m *ParentalSettings) GetApplistCustom() []*ParentalApp {
	if m != nil {
		return m.ApplistCustom
	}
	return nil
}

func (m *ParentalSettings) GetPasswordhashtype() uint32 {
	if m != nil && m.Passwordhashtype != nil {
		return *m.Passwordhashtype
	}
	return 0
}

func (m *ParentalSettings) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *ParentalSettings) GetPasswordhash() []byte {
	if m != nil {
		return m.Passwordhash
	}
	return nil
}

func (m *ParentalSettings) GetIsEnabled() bool {
	if m != nil && m.IsEnabled != nil {
		return *m.IsEnabled
	}
	return false
}

func (m *ParentalSettings) GetEnabledFeatures() uint32 {
	if m != nil && m.EnabledFeatures != nil {
		return *m.EnabledFeatures
	}
	return 0
}

func (m *ParentalSettings) GetRecoveryEmail() string {
	if m != nil && m.RecoveryEmail != nil {
		return *m.RecoveryEmail
	}
	return ""
}

type CParental_EnableParentalSettings_Request struct {
	Password             *string           `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Settings             *ParentalSettings `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
	Sessionid            *string           `protobuf:"bytes,3,opt,name=sessionid" json:"sessionid,omitempty"`
	Enablecode           *uint32           `protobuf:"varint,4,opt,name=enablecode" json:"enablecode,omitempty"`
	Steamid              *uint64           `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CParental_EnableParentalSettings_Request) Reset() {
	*m = CParental_EnableParentalSettings_Request{}
}
func (m *CParental_EnableParentalSettings_Request) String() string { return proto.CompactTextString(m) }
func (*CParental_EnableParentalSettings_Request) ProtoMessage()    {}
func (*CParental_EnableParentalSettings_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{2}
}
func (m *CParental_EnableParentalSettings_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_EnableParentalSettings_Request.Unmarshal(m, b)
}
func (m *CParental_EnableParentalSettings_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_EnableParentalSettings_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_EnableParentalSettings_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_EnableParentalSettings_Request.Merge(dst, src)
}
func (m *CParental_EnableParentalSettings_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_EnableParentalSettings_Request.Size(m)
}
func (m *CParental_EnableParentalSettings_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_EnableParentalSettings_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_EnableParentalSettings_Request proto.InternalMessageInfo

func (m *CParental_EnableParentalSettings_Request) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CParental_EnableParentalSettings_Request) GetSettings() *ParentalSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *CParental_EnableParentalSettings_Request) GetSessionid() string {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return ""
}

func (m *CParental_EnableParentalSettings_Request) GetEnablecode() uint32 {
	if m != nil && m.Enablecode != nil {
		return *m.Enablecode
	}
	return 0
}

func (m *CParental_EnableParentalSettings_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CParental_EnableParentalSettings_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_EnableParentalSettings_Response) Reset() {
	*m = CParental_EnableParentalSettings_Response{}
}
func (m *CParental_EnableParentalSettings_Response) String() string { return proto.CompactTextString(m) }
func (*CParental_EnableParentalSettings_Response) ProtoMessage()    {}
func (*CParental_EnableParentalSettings_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{3}
}
func (m *CParental_EnableParentalSettings_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_EnableParentalSettings_Response.Unmarshal(m, b)
}
func (m *CParental_EnableParentalSettings_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_EnableParentalSettings_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_EnableParentalSettings_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_EnableParentalSettings_Response.Merge(dst, src)
}
func (m *CParental_EnableParentalSettings_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_EnableParentalSettings_Response.Size(m)
}
func (m *CParental_EnableParentalSettings_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_EnableParentalSettings_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_EnableParentalSettings_Response proto.InternalMessageInfo

type CParental_DisableParentalSettings_Request struct {
	Password             *string  `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Steamid              *uint64  `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_DisableParentalSettings_Request) Reset() {
	*m = CParental_DisableParentalSettings_Request{}
}
func (m *CParental_DisableParentalSettings_Request) String() string { return proto.CompactTextString(m) }
func (*CParental_DisableParentalSettings_Request) ProtoMessage()    {}
func (*CParental_DisableParentalSettings_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{4}
}
func (m *CParental_DisableParentalSettings_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_DisableParentalSettings_Request.Unmarshal(m, b)
}
func (m *CParental_DisableParentalSettings_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_DisableParentalSettings_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_DisableParentalSettings_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_DisableParentalSettings_Request.Merge(dst, src)
}
func (m *CParental_DisableParentalSettings_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_DisableParentalSettings_Request.Size(m)
}
func (m *CParental_DisableParentalSettings_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_DisableParentalSettings_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_DisableParentalSettings_Request proto.InternalMessageInfo

func (m *CParental_DisableParentalSettings_Request) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CParental_DisableParentalSettings_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CParental_DisableParentalSettings_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_DisableParentalSettings_Response) Reset() {
	*m = CParental_DisableParentalSettings_Response{}
}
func (m *CParental_DisableParentalSettings_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CParental_DisableParentalSettings_Response) ProtoMessage() {}
func (*CParental_DisableParentalSettings_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{5}
}
func (m *CParental_DisableParentalSettings_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_DisableParentalSettings_Response.Unmarshal(m, b)
}
func (m *CParental_DisableParentalSettings_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_DisableParentalSettings_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_DisableParentalSettings_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_DisableParentalSettings_Response.Merge(dst, src)
}
func (m *CParental_DisableParentalSettings_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_DisableParentalSettings_Response.Size(m)
}
func (m *CParental_DisableParentalSettings_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_DisableParentalSettings_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_DisableParentalSettings_Response proto.InternalMessageInfo

type CParental_GetParentalSettings_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_GetParentalSettings_Request) Reset()         { *m = CParental_GetParentalSettings_Request{} }
func (m *CParental_GetParentalSettings_Request) String() string { return proto.CompactTextString(m) }
func (*CParental_GetParentalSettings_Request) ProtoMessage()    {}
func (*CParental_GetParentalSettings_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{6}
}
func (m *CParental_GetParentalSettings_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_GetParentalSettings_Request.Unmarshal(m, b)
}
func (m *CParental_GetParentalSettings_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_GetParentalSettings_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_GetParentalSettings_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_GetParentalSettings_Request.Merge(dst, src)
}
func (m *CParental_GetParentalSettings_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_GetParentalSettings_Request.Size(m)
}
func (m *CParental_GetParentalSettings_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_GetParentalSettings_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_GetParentalSettings_Request proto.InternalMessageInfo

func (m *CParental_GetParentalSettings_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CParental_GetParentalSettings_Response struct {
	Settings             *ParentalSettings `protobuf:"bytes,1,opt,name=settings" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CParental_GetParentalSettings_Response) Reset() {
	*m = CParental_GetParentalSettings_Response{}
}
func (m *CParental_GetParentalSettings_Response) String() string { return proto.CompactTextString(m) }
func (*CParental_GetParentalSettings_Response) ProtoMessage()    {}
func (*CParental_GetParentalSettings_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{7}
}
func (m *CParental_GetParentalSettings_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_GetParentalSettings_Response.Unmarshal(m, b)
}
func (m *CParental_GetParentalSettings_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_GetParentalSettings_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_GetParentalSettings_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_GetParentalSettings_Response.Merge(dst, src)
}
func (m *CParental_GetParentalSettings_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_GetParentalSettings_Response.Size(m)
}
func (m *CParental_GetParentalSettings_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_GetParentalSettings_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_GetParentalSettings_Response proto.InternalMessageInfo

func (m *CParental_GetParentalSettings_Response) GetSettings() *ParentalSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type CParental_GetSignedParentalSettings_Request struct {
	Priority             *uint32  `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_GetSignedParentalSettings_Request) Reset() {
	*m = CParental_GetSignedParentalSettings_Request{}
}
func (m *CParental_GetSignedParentalSettings_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CParental_GetSignedParentalSettings_Request) ProtoMessage() {}
func (*CParental_GetSignedParentalSettings_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{8}
}
func (m *CParental_GetSignedParentalSettings_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_GetSignedParentalSettings_Request.Unmarshal(m, b)
}
func (m *CParental_GetSignedParentalSettings_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_GetSignedParentalSettings_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_GetSignedParentalSettings_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_GetSignedParentalSettings_Request.Merge(dst, src)
}
func (m *CParental_GetSignedParentalSettings_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_GetSignedParentalSettings_Request.Size(m)
}
func (m *CParental_GetSignedParentalSettings_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_GetSignedParentalSettings_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_GetSignedParentalSettings_Request proto.InternalMessageInfo

func (m *CParental_GetSignedParentalSettings_Request) GetPriority() uint32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

type CParental_GetSignedParentalSettings_Response struct {
	SerializedSettings   []byte   `protobuf:"bytes,1,opt,name=serialized_settings,json=serializedSettings" json:"serialized_settings,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_GetSignedParentalSettings_Response) Reset() {
	*m = CParental_GetSignedParentalSettings_Response{}
}
func (m *CParental_GetSignedParentalSettings_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CParental_GetSignedParentalSettings_Response) ProtoMessage() {}
func (*CParental_GetSignedParentalSettings_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{9}
}
func (m *CParental_GetSignedParentalSettings_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_GetSignedParentalSettings_Response.Unmarshal(m, b)
}
func (m *CParental_GetSignedParentalSettings_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_GetSignedParentalSettings_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_GetSignedParentalSettings_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_GetSignedParentalSettings_Response.Merge(dst, src)
}
func (m *CParental_GetSignedParentalSettings_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_GetSignedParentalSettings_Response.Size(m)
}
func (m *CParental_GetSignedParentalSettings_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_GetSignedParentalSettings_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_GetSignedParentalSettings_Response proto.InternalMessageInfo

func (m *CParental_GetSignedParentalSettings_Response) GetSerializedSettings() []byte {
	if m != nil {
		return m.SerializedSettings
	}
	return nil
}

func (m *CParental_GetSignedParentalSettings_Response) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type CParental_SetParentalSettings_Request struct {
	Password             *string           `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Settings             *ParentalSettings `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
	NewPassword          *string           `protobuf:"bytes,3,opt,name=new_password,json=newPassword" json:"new_password,omitempty"`
	Sessionid            *string           `protobuf:"bytes,4,opt,name=sessionid" json:"sessionid,omitempty"`
	Steamid              *uint64           `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CParental_SetParentalSettings_Request) Reset()         { *m = CParental_SetParentalSettings_Request{} }
func (m *CParental_SetParentalSettings_Request) String() string { return proto.CompactTextString(m) }
func (*CParental_SetParentalSettings_Request) ProtoMessage()    {}
func (*CParental_SetParentalSettings_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{10}
}
func (m *CParental_SetParentalSettings_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_SetParentalSettings_Request.Unmarshal(m, b)
}
func (m *CParental_SetParentalSettings_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_SetParentalSettings_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_SetParentalSettings_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_SetParentalSettings_Request.Merge(dst, src)
}
func (m *CParental_SetParentalSettings_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_SetParentalSettings_Request.Size(m)
}
func (m *CParental_SetParentalSettings_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_SetParentalSettings_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_SetParentalSettings_Request proto.InternalMessageInfo

func (m *CParental_SetParentalSettings_Request) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CParental_SetParentalSettings_Request) GetSettings() *ParentalSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *CParental_SetParentalSettings_Request) GetNewPassword() string {
	if m != nil && m.NewPassword != nil {
		return *m.NewPassword
	}
	return ""
}

func (m *CParental_SetParentalSettings_Request) GetSessionid() string {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return ""
}

func (m *CParental_SetParentalSettings_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CParental_SetParentalSettings_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_SetParentalSettings_Response) Reset() {
	*m = CParental_SetParentalSettings_Response{}
}
func (m *CParental_SetParentalSettings_Response) String() string { return proto.CompactTextString(m) }
func (*CParental_SetParentalSettings_Response) ProtoMessage()    {}
func (*CParental_SetParentalSettings_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{11}
}
func (m *CParental_SetParentalSettings_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_SetParentalSettings_Response.Unmarshal(m, b)
}
func (m *CParental_SetParentalSettings_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_SetParentalSettings_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_SetParentalSettings_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_SetParentalSettings_Response.Merge(dst, src)
}
func (m *CParental_SetParentalSettings_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_SetParentalSettings_Response.Size(m)
}
func (m *CParental_SetParentalSettings_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_SetParentalSettings_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_SetParentalSettings_Response proto.InternalMessageInfo

type CParental_ValidateToken_Request struct {
	UnlockToken          *string  `protobuf:"bytes,1,opt,name=unlock_token,json=unlockToken" json:"unlock_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_ValidateToken_Request) Reset()         { *m = CParental_ValidateToken_Request{} }
func (m *CParental_ValidateToken_Request) String() string { return proto.CompactTextString(m) }
func (*CParental_ValidateToken_Request) ProtoMessage()    {}
func (*CParental_ValidateToken_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{12}
}
func (m *CParental_ValidateToken_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_ValidateToken_Request.Unmarshal(m, b)
}
func (m *CParental_ValidateToken_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_ValidateToken_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_ValidateToken_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_ValidateToken_Request.Merge(dst, src)
}
func (m *CParental_ValidateToken_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_ValidateToken_Request.Size(m)
}
func (m *CParental_ValidateToken_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_ValidateToken_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_ValidateToken_Request proto.InternalMessageInfo

func (m *CParental_ValidateToken_Request) GetUnlockToken() string {
	if m != nil && m.UnlockToken != nil {
		return *m.UnlockToken
	}
	return ""
}

type CParental_ValidateToken_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_ValidateToken_Response) Reset()         { *m = CParental_ValidateToken_Response{} }
func (m *CParental_ValidateToken_Response) String() string { return proto.CompactTextString(m) }
func (*CParental_ValidateToken_Response) ProtoMessage()    {}
func (*CParental_ValidateToken_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{13}
}
func (m *CParental_ValidateToken_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_ValidateToken_Response.Unmarshal(m, b)
}
func (m *CParental_ValidateToken_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_ValidateToken_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_ValidateToken_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_ValidateToken_Response.Merge(dst, src)
}
func (m *CParental_ValidateToken_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_ValidateToken_Response.Size(m)
}
func (m *CParental_ValidateToken_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_ValidateToken_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_ValidateToken_Response proto.InternalMessageInfo

type CParental_ValidatePassword_Request struct {
	Password             *string  `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Session              *string  `protobuf:"bytes,2,opt,name=session" json:"session,omitempty"`
	SendUnlockOnSuccess  *bool    `protobuf:"varint,3,opt,name=send_unlock_on_success,json=sendUnlockOnSuccess" json:"send_unlock_on_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_ValidatePassword_Request) Reset()         { *m = CParental_ValidatePassword_Request{} }
func (m *CParental_ValidatePassword_Request) String() string { return proto.CompactTextString(m) }
func (*CParental_ValidatePassword_Request) ProtoMessage()    {}
func (*CParental_ValidatePassword_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{14}
}
func (m *CParental_ValidatePassword_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_ValidatePassword_Request.Unmarshal(m, b)
}
func (m *CParental_ValidatePassword_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_ValidatePassword_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_ValidatePassword_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_ValidatePassword_Request.Merge(dst, src)
}
func (m *CParental_ValidatePassword_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_ValidatePassword_Request.Size(m)
}
func (m *CParental_ValidatePassword_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_ValidatePassword_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_ValidatePassword_Request proto.InternalMessageInfo

func (m *CParental_ValidatePassword_Request) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CParental_ValidatePassword_Request) GetSession() string {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return ""
}

func (m *CParental_ValidatePassword_Request) GetSendUnlockOnSuccess() bool {
	if m != nil && m.SendUnlockOnSuccess != nil {
		return *m.SendUnlockOnSuccess
	}
	return false
}

type CParental_ValidatePassword_Response struct {
	Token                *string  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_ValidatePassword_Response) Reset()         { *m = CParental_ValidatePassword_Response{} }
func (m *CParental_ValidatePassword_Response) String() string { return proto.CompactTextString(m) }
func (*CParental_ValidatePassword_Response) ProtoMessage()    {}
func (*CParental_ValidatePassword_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{15}
}
func (m *CParental_ValidatePassword_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_ValidatePassword_Response.Unmarshal(m, b)
}
func (m *CParental_ValidatePassword_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_ValidatePassword_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_ValidatePassword_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_ValidatePassword_Response.Merge(dst, src)
}
func (m *CParental_ValidatePassword_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_ValidatePassword_Response.Size(m)
}
func (m *CParental_ValidatePassword_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_ValidatePassword_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_ValidatePassword_Response proto.InternalMessageInfo

func (m *CParental_ValidatePassword_Response) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type CParental_LockClient_Request struct {
	Session              *string  `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_LockClient_Request) Reset()         { *m = CParental_LockClient_Request{} }
func (m *CParental_LockClient_Request) String() string { return proto.CompactTextString(m) }
func (*CParental_LockClient_Request) ProtoMessage()    {}
func (*CParental_LockClient_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{16}
}
func (m *CParental_LockClient_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_LockClient_Request.Unmarshal(m, b)
}
func (m *CParental_LockClient_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_LockClient_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_LockClient_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_LockClient_Request.Merge(dst, src)
}
func (m *CParental_LockClient_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_LockClient_Request.Size(m)
}
func (m *CParental_LockClient_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_LockClient_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_LockClient_Request proto.InternalMessageInfo

func (m *CParental_LockClient_Request) GetSession() string {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return ""
}

type CParental_LockClient_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_LockClient_Response) Reset()         { *m = CParental_LockClient_Response{} }
func (m *CParental_LockClient_Response) String() string { return proto.CompactTextString(m) }
func (*CParental_LockClient_Response) ProtoMessage()    {}
func (*CParental_LockClient_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{17}
}
func (m *CParental_LockClient_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_LockClient_Response.Unmarshal(m, b)
}
func (m *CParental_LockClient_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_LockClient_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_LockClient_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_LockClient_Response.Merge(dst, src)
}
func (m *CParental_LockClient_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_LockClient_Response.Size(m)
}
func (m *CParental_LockClient_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_LockClient_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_LockClient_Response proto.InternalMessageInfo

type CParental_RequestRecoveryCode_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_RequestRecoveryCode_Request) Reset()         { *m = CParental_RequestRecoveryCode_Request{} }
func (m *CParental_RequestRecoveryCode_Request) String() string { return proto.CompactTextString(m) }
func (*CParental_RequestRecoveryCode_Request) ProtoMessage()    {}
func (*CParental_RequestRecoveryCode_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{18}
}
func (m *CParental_RequestRecoveryCode_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_RequestRecoveryCode_Request.Unmarshal(m, b)
}
func (m *CParental_RequestRecoveryCode_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_RequestRecoveryCode_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_RequestRecoveryCode_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_RequestRecoveryCode_Request.Merge(dst, src)
}
func (m *CParental_RequestRecoveryCode_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_RequestRecoveryCode_Request.Size(m)
}
func (m *CParental_RequestRecoveryCode_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_RequestRecoveryCode_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_RequestRecoveryCode_Request proto.InternalMessageInfo

type CParental_RequestRecoveryCode_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_RequestRecoveryCode_Response) Reset() {
	*m = CParental_RequestRecoveryCode_Response{}
}
func (m *CParental_RequestRecoveryCode_Response) String() string { return proto.CompactTextString(m) }
func (*CParental_RequestRecoveryCode_Response) ProtoMessage()    {}
func (*CParental_RequestRecoveryCode_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{19}
}
func (m *CParental_RequestRecoveryCode_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_RequestRecoveryCode_Response.Unmarshal(m, b)
}
func (m *CParental_RequestRecoveryCode_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_RequestRecoveryCode_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_RequestRecoveryCode_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_RequestRecoveryCode_Response.Merge(dst, src)
}
func (m *CParental_RequestRecoveryCode_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_RequestRecoveryCode_Response.Size(m)
}
func (m *CParental_RequestRecoveryCode_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_RequestRecoveryCode_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_RequestRecoveryCode_Response proto.InternalMessageInfo

type CParental_DisableWithRecoveryCode_Request struct {
	RecoveryCode         *uint32  `protobuf:"varint,1,opt,name=recovery_code,json=recoveryCode" json:"recovery_code,omitempty"`
	Steamid              *uint64  `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_DisableWithRecoveryCode_Request) Reset() {
	*m = CParental_DisableWithRecoveryCode_Request{}
}
func (m *CParental_DisableWithRecoveryCode_Request) String() string { return proto.CompactTextString(m) }
func (*CParental_DisableWithRecoveryCode_Request) ProtoMessage()    {}
func (*CParental_DisableWithRecoveryCode_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{20}
}
func (m *CParental_DisableWithRecoveryCode_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_DisableWithRecoveryCode_Request.Unmarshal(m, b)
}
func (m *CParental_DisableWithRecoveryCode_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_DisableWithRecoveryCode_Request.Marshal(b, m, deterministic)
}
func (dst *CParental_DisableWithRecoveryCode_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_DisableWithRecoveryCode_Request.Merge(dst, src)
}
func (m *CParental_DisableWithRecoveryCode_Request) XXX_Size() int {
	return xxx_messageInfo_CParental_DisableWithRecoveryCode_Request.Size(m)
}
func (m *CParental_DisableWithRecoveryCode_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_DisableWithRecoveryCode_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_DisableWithRecoveryCode_Request proto.InternalMessageInfo

func (m *CParental_DisableWithRecoveryCode_Request) GetRecoveryCode() uint32 {
	if m != nil && m.RecoveryCode != nil {
		return *m.RecoveryCode
	}
	return 0
}

func (m *CParental_DisableWithRecoveryCode_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CParental_DisableWithRecoveryCode_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_DisableWithRecoveryCode_Response) Reset() {
	*m = CParental_DisableWithRecoveryCode_Response{}
}
func (m *CParental_DisableWithRecoveryCode_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CParental_DisableWithRecoveryCode_Response) ProtoMessage() {}
func (*CParental_DisableWithRecoveryCode_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{21}
}
func (m *CParental_DisableWithRecoveryCode_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_DisableWithRecoveryCode_Response.Unmarshal(m, b)
}
func (m *CParental_DisableWithRecoveryCode_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_DisableWithRecoveryCode_Response.Marshal(b, m, deterministic)
}
func (dst *CParental_DisableWithRecoveryCode_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_DisableWithRecoveryCode_Response.Merge(dst, src)
}
func (m *CParental_DisableWithRecoveryCode_Response) XXX_Size() int {
	return xxx_messageInfo_CParental_DisableWithRecoveryCode_Response.Size(m)
}
func (m *CParental_DisableWithRecoveryCode_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_DisableWithRecoveryCode_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_DisableWithRecoveryCode_Response proto.InternalMessageInfo

type CParental_ParentalSettingsChange_Notification struct {
	SerializedSettings   []byte   `protobuf:"bytes,1,opt,name=serialized_settings,json=serializedSettings" json:"serialized_settings,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Password             *string  `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Sessionid            *string  `protobuf:"bytes,4,opt,name=sessionid" json:"sessionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_ParentalSettingsChange_Notification) Reset() {
	*m = CParental_ParentalSettingsChange_Notification{}
}
func (m *CParental_ParentalSettingsChange_Notification) String() string {
	return proto.CompactTextString(m)
}
func (*CParental_ParentalSettingsChange_Notification) ProtoMessage() {}
func (*CParental_ParentalSettingsChange_Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{22}
}
func (m *CParental_ParentalSettingsChange_Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_ParentalSettingsChange_Notification.Unmarshal(m, b)
}
func (m *CParental_ParentalSettingsChange_Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_ParentalSettingsChange_Notification.Marshal(b, m, deterministic)
}
func (dst *CParental_ParentalSettingsChange_Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_ParentalSettingsChange_Notification.Merge(dst, src)
}
func (m *CParental_ParentalSettingsChange_Notification) XXX_Size() int {
	return xxx_messageInfo_CParental_ParentalSettingsChange_Notification.Size(m)
}
func (m *CParental_ParentalSettingsChange_Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_ParentalSettingsChange_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_ParentalSettingsChange_Notification proto.InternalMessageInfo

func (m *CParental_ParentalSettingsChange_Notification) GetSerializedSettings() []byte {
	if m != nil {
		return m.SerializedSettings
	}
	return nil
}

func (m *CParental_ParentalSettingsChange_Notification) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *CParental_ParentalSettingsChange_Notification) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CParental_ParentalSettingsChange_Notification) GetSessionid() string {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return ""
}

type CParental_ParentalUnlock_Notification struct {
	Password             *string  `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Sessionid            *string  `protobuf:"bytes,2,opt,name=sessionid" json:"sessionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_ParentalUnlock_Notification) Reset()         { *m = CParental_ParentalUnlock_Notification{} }
func (m *CParental_ParentalUnlock_Notification) String() string { return proto.CompactTextString(m) }
func (*CParental_ParentalUnlock_Notification) ProtoMessage()    {}
func (*CParental_ParentalUnlock_Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{23}
}
func (m *CParental_ParentalUnlock_Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_ParentalUnlock_Notification.Unmarshal(m, b)
}
func (m *CParental_ParentalUnlock_Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_ParentalUnlock_Notification.Marshal(b, m, deterministic)
}
func (dst *CParental_ParentalUnlock_Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_ParentalUnlock_Notification.Merge(dst, src)
}
func (m *CParental_ParentalUnlock_Notification) XXX_Size() int {
	return xxx_messageInfo_CParental_ParentalUnlock_Notification.Size(m)
}
func (m *CParental_ParentalUnlock_Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_ParentalUnlock_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_ParentalUnlock_Notification proto.InternalMessageInfo

func (m *CParental_ParentalUnlock_Notification) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CParental_ParentalUnlock_Notification) GetSessionid() string {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return ""
}

type CParental_ParentalLock_Notification struct {
	Sessionid            *string  `protobuf:"bytes,1,opt,name=sessionid" json:"sessionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CParental_ParentalLock_Notification) Reset()         { *m = CParental_ParentalLock_Notification{} }
func (m *CParental_ParentalLock_Notification) String() string { return proto.CompactTextString(m) }
func (*CParental_ParentalLock_Notification) ProtoMessage()    {}
func (*CParental_ParentalLock_Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_steammessages_parental_steamclient_f108560368836c2d, []int{24}
}
func (m *CParental_ParentalLock_Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CParental_ParentalLock_Notification.Unmarshal(m, b)
}
func (m *CParental_ParentalLock_Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CParental_ParentalLock_Notification.Marshal(b, m, deterministic)
}
func (dst *CParental_ParentalLock_Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CParental_ParentalLock_Notification.Merge(dst, src)
}
func (m *CParental_ParentalLock_Notification) XXX_Size() int {
	return xxx_messageInfo_CParental_ParentalLock_Notification.Size(m)
}
func (m *CParental_ParentalLock_Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_CParental_ParentalLock_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_CParental_ParentalLock_Notification proto.InternalMessageInfo

func (m *CParental_ParentalLock_Notification) GetSessionid() string {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return ""
}

func init() {
	proto.RegisterType((*ParentalApp)(nil), "ParentalApp")
	proto.RegisterType((*ParentalSettings)(nil), "ParentalSettings")
	proto.RegisterType((*CParental_EnableParentalSettings_Request)(nil), "CParental_EnableParentalSettings_Request")
	proto.RegisterType((*CParental_EnableParentalSettings_Response)(nil), "CParental_EnableParentalSettings_Response")
	proto.RegisterType((*CParental_DisableParentalSettings_Request)(nil), "CParental_DisableParentalSettings_Request")
	proto.RegisterType((*CParental_DisableParentalSettings_Response)(nil), "CParental_DisableParentalSettings_Response")
	proto.RegisterType((*CParental_GetParentalSettings_Request)(nil), "CParental_GetParentalSettings_Request")
	proto.RegisterType((*CParental_GetParentalSettings_Response)(nil), "CParental_GetParentalSettings_Response")
	proto.RegisterType((*CParental_GetSignedParentalSettings_Request)(nil), "CParental_GetSignedParentalSettings_Request")
	proto.RegisterType((*CParental_GetSignedParentalSettings_Response)(nil), "CParental_GetSignedParentalSettings_Response")
	proto.RegisterType((*CParental_SetParentalSettings_Request)(nil), "CParental_SetParentalSettings_Request")
	proto.RegisterType((*CParental_SetParentalSettings_Response)(nil), "CParental_SetParentalSettings_Response")
	proto.RegisterType((*CParental_ValidateToken_Request)(nil), "CParental_ValidateToken_Request")
	proto.RegisterType((*CParental_ValidateToken_Response)(nil), "CParental_ValidateToken_Response")
	proto.RegisterType((*CParental_ValidatePassword_Request)(nil), "CParental_ValidatePassword_Request")
	proto.RegisterType((*CParental_ValidatePassword_Response)(nil), "CParental_ValidatePassword_Response")
	proto.RegisterType((*CParental_LockClient_Request)(nil), "CParental_LockClient_Request")
	proto.RegisterType((*CParental_LockClient_Response)(nil), "CParental_LockClient_Response")
	proto.RegisterType((*CParental_RequestRecoveryCode_Request)(nil), "CParental_RequestRecoveryCode_Request")
	proto.RegisterType((*CParental_RequestRecoveryCode_Response)(nil), "CParental_RequestRecoveryCode_Response")
	proto.RegisterType((*CParental_DisableWithRecoveryCode_Request)(nil), "CParental_DisableWithRecoveryCode_Request")
	proto.RegisterType((*CParental_DisableWithRecoveryCode_Response)(nil), "CParental_DisableWithRecoveryCode_Response")
	proto.RegisterType((*CParental_ParentalSettingsChange_Notification)(nil), "CParental_ParentalSettingsChange_Notification")
	proto.RegisterType((*CParental_ParentalUnlock_Notification)(nil), "CParental_ParentalUnlock_Notification")
	proto.RegisterType((*CParental_ParentalLock_Notification)(nil), "CParental_ParentalLock_Notification")
}

func init() {
	proto.RegisterFile("steammessages_parental.steamclient.proto", fileDescriptor_steammessages_parental_steamclient_f108560368836c2d)
}

var fileDescriptor_steammessages_parental_steamclient_f108560368836c2d = []byte{
	// 1516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcf, 0x6f, 0x13, 0xc7,
	0x17, 0xd7, 0x92, 0x00, 0xc9, 0xd8, 0x09, 0xf9, 0x4e, 0x10, 0xdf, 0xc5, 0x22, 0x30, 0x2c, 0x10,
	0x0c, 0x24, 0x1b, 0x7d, 0x13, 0xe9, 0x0b, 0x12, 0x55, 0xab, 0xc4, 0x50, 0x8a, 0x4a, 0x81, 0xda,
	0xb4, 0x54, 0xe5, 0xb0, 0x9a, 0xec, 0x3e, 0xdb, 0x43, 0xec, 0x99, 0xed, 0xce, 0x38, 0x69, 0x2a,
	0x55, 0xaa, 0x7c, 0xe8, 0xad, 0xe2, 0xd2, 0x63, 0xef, 0x48, 0xed, 0x79, 0xd5, 0x1e, 0x2b, 0xf5,
	0xd4, 0x43, 0xa5, 0xaa, 0x7f, 0x45, 0xff, 0x8c, 0x6a, 0x67, 0x77, 0xed, 0x5d, 0xc7, 0xbf, 0x52,
	0xb8, 0xed, 0xbc, 0x79, 0xf3, 0xe6, 0xf3, 0xe6, 0x7d, 0x66, 0x3e, 0xcf, 0x46, 0x65, 0xa9, 0x80,
	0xb6, 0xdb, 0x20, 0x25, 0x6d, 0x80, 0x74, 0x7c, 0x1a, 0x00, 0x57, 0xb4, 0x65, 0x6b, 0xb3, 0xdb,
	0x62, 0xc0, 0x95, 0xed, 0x07, 0x42, 0x89, 0xd2, 0x5a, 0xde, 0xb3, 0xc3, 0x59, 0x9d, 0x81, 0xe7,
	0xec, 0x52, 0x09, 0x47, 0xbd, 0xad, 0x1d, 0x54, 0x78, 0x9a, 0xc4, 0xda, 0xf6, 0x7d, 0x7c, 0x16,
	0x9d, 0xa4, 0xbe, 0xcf, 0x3c, 0xd3, 0x20, 0x46, 0x79, 0xa1, 0x1a, 0x0f, 0xf0, 0x0a, 0x42, 0x4c,
	0x3a, 0xb4, 0xd5, 0x12, 0x07, 0xe0, 0x99, 0x27, 0x88, 0x51, 0x9e, 0xab, 0xce, 0x33, 0xb9, 0x1d,
	0x1b, 0xac, 0xdf, 0x67, 0xd0, 0x52, 0x1a, 0xa4, 0x06, 0x4a, 0x31, 0xde, 0x90, 0xd8, 0x44, 0xa7,
	0xf5, 0x6e, 0x49, 0xac, 0x53, 0xd5, 0x74, 0x88, 0x57, 0xd1, 0x19, 0xea, 0xfb, 0x2d, 0x26, 0x95,
	0x06, 0xe5, 0xb0, 0x38, 0xe4, 0x42, 0x75, 0x21, 0x31, 0xef, 0x50, 0x09, 0x0f, 0x3d, 0x7c, 0x07,
	0x99, 0x39, 0x3f, 0x0f, 0xa4, 0x1b, 0x30, 0x5f, 0x31, 0xc1, 0xcd, 0x19, 0x62, 0x94, 0xe7, 0xab,
	0xe7, 0x32, 0x0b, 0xee, 0xf5, 0x67, 0xf1, 0x06, 0x2a, 0x66, 0x57, 0x9a, 0xb3, 0x64, 0xa6, 0x5c,
	0xd8, 0x2c, 0xda, 0x99, 0x4c, 0xab, 0x85, 0xcc, 0x5a, 0xbc, 0x85, 0x16, 0xd3, 0x05, 0x6e, 0x47,
	0x2a, 0xd1, 0x36, 0x4f, 0x0e, 0x59, 0x92, 0xe2, 0xab, 0x68, 0x17, 0x7c, 0x13, 0x2d, 0xf9, 0x54,
	0xca, 0x03, 0x11, 0x78, 0x4d, 0x2a, 0x9b, 0xea, 0xd0, 0x07, 0xf3, 0x94, 0x4e, 0xe4, 0x88, 0x1d,
	0x63, 0x34, 0x2b, 0x69, 0x4b, 0x99, 0xa7, 0x89, 0x51, 0x2e, 0x56, 0xf5, 0x37, 0xb6, 0x50, 0x31,
	0xeb, 0x67, 0xce, 0xe9, 0xb9, 0x9c, 0x2d, 0x39, 0x79, 0xe0, 0x74, 0xb7, 0x05, 0x9e, 0x39, 0x9f,
	0x9e, 0xfc, 0xfd, 0xd8, 0x80, 0x6f, 0xa0, 0xa5, 0x64, 0xce, 0xa9, 0x03, 0x55, 0x9d, 0x00, 0xa4,
	0x89, 0x34, 0x84, 0x33, 0x89, 0xfd, 0xfd, 0xc4, 0x8c, 0xaf, 0xa1, 0xc5, 0x00, 0x5c, 0xb1, 0x0f,
	0xc1, 0xa1, 0x03, 0x6d, 0xca, 0x5a, 0x66, 0x41, 0x9f, 0xe1, 0x42, 0x6a, 0xbd, 0x1f, 0x19, 0xad,
	0x3f, 0x0c, 0x54, 0xae, 0xa4, 0x49, 0x3b, 0xf1, 0x3e, 0x83, 0xb5, 0x75, 0xaa, 0xf0, 0x45, 0x07,
	0xa4, 0xc2, 0x25, 0x34, 0x97, 0xa2, 0xd5, 0x45, 0x9e, 0xaf, 0xf6, 0xc6, 0x78, 0x1d, 0xcd, 0xc9,
	0xc4, 0x5f, 0x97, 0xb7, 0xb0, 0xf9, 0x1f, 0x7b, 0x30, 0x50, 0xb5, 0xe7, 0x82, 0x2f, 0xa0, 0x79,
	0x09, 0x52, 0x32, 0xc1, 0x99, 0x97, 0x54, 0xb7, 0x6f, 0xc0, 0x17, 0x11, 0x8a, 0xf3, 0x71, 0x85,
	0x17, 0x95, 0x33, 0xca, 0x30, 0x63, 0xc9, 0x92, 0x0d, 0xe5, 0xc8, 0x66, 0xdd, 0x42, 0x37, 0xa6,
	0x48, 0x47, 0xfa, 0x82, 0x4b, 0xb0, 0x68, 0xd6, 0xf9, 0x1e, 0x93, 0xff, 0x3a, 0xf9, 0xd1, 0x78,
	0xd6, 0xd0, 0xcd, 0x69, 0xb6, 0x48, 0x00, 0x6d, 0xa3, 0x6b, 0x7d, 0xef, 0x07, 0xa0, 0x46, 0x82,
	0x19, 0xbd, 0xe1, 0x73, 0xb4, 0x3a, 0x29, 0x44, 0xbc, 0x59, 0xae, 0x62, 0xc6, 0xc4, 0x8a, 0x59,
	0x0f, 0xd1, 0xad, 0x5c, 0xe0, 0x1a, 0x6b, 0x70, 0xf0, 0xc6, 0x1e, 0x57, 0xc0, 0x44, 0xc0, 0xd4,
	0x61, 0xf2, 0xb8, 0xf4, 0xc6, 0xd6, 0xd7, 0x68, 0x6d, 0xba, 0x50, 0x09, 0xd2, 0x0d, 0xb4, 0x2c,
	0x21, 0x60, 0xb4, 0xc5, 0xbe, 0x02, 0xcf, 0xc9, 0x81, 0x2e, 0x56, 0x71, 0x7f, 0xaa, 0x96, 0x65,
	0x17, 0x6b, 0x70, 0x7d, 0x15, 0x34, 0x1b, 0x8b, 0xd5, 0xbe, 0x21, 0xe2, 0x7c, 0xe6, 0x98, 0x6b,
	0x63, 0x8e, 0xf9, 0x2d, 0x12, 0xfe, 0x32, 0x2a, 0x72, 0x38, 0x70, 0x7a, 0xe1, 0x62, 0xce, 0x17,
	0x38, 0x1c, 0x3c, 0x4d, 0x23, 0xe6, 0xee, 0xc4, 0xec, 0xe0, 0x9d, 0x18, 0x5d, 0xf2, 0x72, 0xb6,
	0xe4, 0xb5, 0x31, 0x25, 0xb7, 0xee, 0xa1, 0x4b, 0x7d, 0xcf, 0x4f, 0x69, 0x8b, 0x79, 0x54, 0xc1,
	0x33, 0xb1, 0x07, 0xbc, 0x97, 0xf2, 0x65, 0x54, 0xec, 0xf0, 0x96, 0x70, 0xf7, 0x1c, 0x15, 0xd9,
	0x93, 0xb4, 0x0b, 0xb1, 0x4d, 0xbb, 0x5a, 0x16, 0x22, 0xa3, 0xa3, 0x24, 0x3b, 0xbd, 0x32, 0x90,
	0x75, 0xd4, 0x29, 0x4d, 0x75, 0xea, 0x4b, 0x15, 0x67, 0xaf, 0xcf, 0x77, 0xbe, 0x9a, 0x0e, 0xf1,
	0x16, 0x3a, 0x27, 0x81, 0x7b, 0x4e, 0x02, 0x54, 0x70, 0x47, 0x76, 0x5c, 0x17, 0xa4, 0xd4, 0xa7,
	0x3a, 0x57, 0x5d, 0x8e, 0x66, 0x3f, 0xd1, 0x93, 0x4f, 0x78, 0x2d, 0x9e, 0xb2, 0xee, 0xa2, 0x2b,
	0x63, 0x01, 0x25, 0x5c, 0x3b, 0x8b, 0x4e, 0x66, 0x13, 0x8f, 0x07, 0xd6, 0x1d, 0x74, 0xa1, 0xbf,
	0xf8, 0x91, 0x70, 0xf7, 0x2a, 0x5a, 0x54, 0x73, 0xf7, 0x31, 0xc1, 0x6a, 0xe4, 0xb0, 0x5a, 0x97,
	0xd0, 0xca, 0x88, 0x95, 0xc9, 0x49, 0x5d, 0xcf, 0x92, 0x31, 0x89, 0x57, 0x4d, 0xde, 0xe8, 0x8a,
	0xf0, 0x20, 0xb5, 0xe5, 0xcb, 0x3c, 0xdc, 0x31, 0x09, 0xf9, 0x72, 0xc8, 0xbb, 0xf6, 0x9c, 0xa9,
	0xe6, 0xb0, 0xb0, 0xf8, 0x0a, 0xea, 0x49, 0x82, 0xa3, 0x9f, 0xdb, 0xf8, 0xb6, 0x16, 0x83, 0x8c,
	0xf3, 0x31, 0x1f, 0xb8, 0x21, 0x7b, 0x25, 0xc8, 0x7e, 0x31, 0xd0, 0x7a, 0xdf, 0x7d, 0x90, 0xa8,
	0x95, 0x26, 0xe5, 0x0d, 0x70, 0x1e, 0x0b, 0xc5, 0xea, 0xcc, 0xa5, 0x89, 0xb6, 0xbf, 0xcd, 0xbb,
	0x9f, 0x23, 0xdc, 0xcc, 0x00, 0xe1, 0xc6, 0xde, 0x3f, 0x8b, 0x66, 0xeb, 0x94, 0x7e, 0xc4, 0x24,
	0xcb, 0x23, 0x1e, 0xc7, 0xe9, 0xdc, 0x16, 0x27, 0x06, 0xb7, 0xa8, 0x64, 0x29, 0x9a, 0x7e, 0x3c,
	0x3a, 0xb2, 0x41, 0x2e, 0x88, 0x31, 0x10, 0x64, 0xf3, 0xaf, 0x45, 0x34, 0x97, 0xae, 0xc5, 0x7f,
	0x1a, 0xe8, 0xdc, 0x70, 0x15, 0xc4, 0x37, 0xec, 0x69, 0x75, 0xbf, 0x74, 0xd3, 0x9e, 0x5e, 0x53,
	0x9d, 0x6e, 0x68, 0xbe, 0x88, 0x9d, 0x48, 0xda, 0xb5, 0x92, 0xb4, 0x6c, 0xa4, 0x2e, 0x02, 0xa2,
	0x9a, 0x40, 0x5a, 0xa2, 0xd1, 0x00, 0x8f, 0x30, 0x4e, 0xa8, 0xeb, 0x8a, 0x0e, 0x57, 0x6b, 0x44,
	0xe8, 0x5e, 0x8e, 0xb6, 0x5a, 0x87, 0xa9, 0xbb, 0xf6, 0x74, 0x3b, 0x41, 0x14, 0xa4, 0x17, 0x02,
	0xff, 0x64, 0xa0, 0xff, 0x8e, 0x10, 0x52, 0x9c, 0x05, 0x3a, 0x41, 0xcf, 0x4b, 0xb7, 0xec, 0x63,
	0x08, 0xf3, 0xed, 0x6e, 0x68, 0x6e, 0x25, 0x5e, 0xc7, 0x49, 0x0b, 0xbf, 0x36, 0xd0, 0xf2, 0x10,
	0x15, 0xc6, 0xab, 0xf6, 0x54, 0x42, 0x5f, 0xba, 0x6e, 0x4f, 0xa7, 0xe6, 0xd6, 0x7b, 0xdd, 0xd0,
	0xbc, 0xfb, 0x00, 0x54, 0xee, 0xd0, 0x8e, 0x83, 0xf4, 0x6f, 0x03, 0x9d, 0x1f, 0xa9, 0xc5, 0x78,
	0xcd, 0x3e, 0x86, 0xf8, 0x97, 0xd6, 0xed, 0xe3, 0xe8, 0xbb, 0xc5, 0xbb, 0xa1, 0xf9, 0xf2, 0x0d,
	0xb0, 0xeb, 0xcf, 0x68, 0xba, 0x4d, 0x54, 0x93, 0x2a, 0xe2, 0x52, 0x4e, 0x76, 0x0f, 0xc9, 0x3e,
	0x04, 0xfa, 0xb7, 0x50, 0xf4, 0x1d, 0xad, 0x0b, 0xc0, 0x05, 0xb6, 0x0f, 0x81, 0x2e, 0x4a, 0x6d,
	0x42, 0x51, 0x6a, 0x53, 0x16, 0xa5, 0x36, 0xb1, 0x28, 0xb5, 0x37, 0x28, 0xca, 0x6b, 0x03, 0x2d,
	0xe4, 0x14, 0x16, 0x13, 0x7b, 0x82, 0x82, 0x97, 0x2e, 0xdb, 0x13, 0xd5, 0xf9, 0xe3, 0x6e, 0x68,
	0x7e, 0x54, 0x69, 0x82, 0xbb, 0x47, 0x58, 0x5d, 0x6f, 0xdd, 0x60, 0xfb, 0xc0, 0xfb, 0xd0, 0x62,
	0x65, 0x25, 0x5a, 0xfc, 0x08, 0x93, 0xc4, 0x15, 0x41, 0x00, 0xae, 0x1a, 0x83, 0xf4, 0x67, 0x03,
	0x2d, 0x0d, 0xaa, 0x2a, 0xbe, 0x62, 0x4f, 0xee, 0x01, 0x4a, 0x57, 0xed, 0x29, 0x74, 0xd9, 0xfa,
	0xac, 0x1b, 0x9a, 0xcf, 0xd2, 0x69, 0x8d, 0xc1, 0x6f, 0x51, 0xc6, 0x15, 0x7c, 0x19, 0x9d, 0x68,
	0xec, 0x3d, 0x86, 0x21, 0x94, 0x7b, 0x24, 0x00, 0xd5, 0x09, 0x38, 0xa1, 0x3c, 0x97, 0x1e, 0x7e,
	0x65, 0x20, 0xd4, 0x17, 0x66, 0xbc, 0x62, 0x8f, 0x53, 0xfa, 0xd2, 0x45, 0x7b, 0xbc, 0x9c, 0xef,
	0x74, 0x43, 0xf3, 0x5d, 0xfd, 0x5c, 0x1f, 0x12, 0x57, 0x70, 0x0e, 0xae, 0x02, 0x8f, 0xc4, 0xbf,
	0xc1, 0x65, 0x4c, 0x4f, 0x4a, 0xf4, 0xee, 0x4d, 0x2a, 0x89, 0x70, 0x35, 0x2b, 0x62, 0xa8, 0x64,
	0x37, 0x10, 0x07, 0x12, 0x02, 0xfc, 0x9b, 0x81, 0x96, 0x87, 0x08, 0x7c, 0x8e, 0x9f, 0x63, 0x3a,
	0x85, 0x1c, 0x3f, 0xc7, 0x36, 0x0a, 0x2f, 0xba, 0xa1, 0xf9, 0x3c, 0xf1, 0x20, 0x94, 0xa4, 0x92,
	0x4f, 0xa2, 0x3e, 0x80, 0xec, 0x02, 0x91, 0x11, 0x5f, 0x95, 0x48, 0x6f, 0x4f, 0x3c, 0xa9, 0x7f,
	0x4d, 0x12, 0xea, 0x79, 0x01, 0xc8, 0x3e, 0x77, 0xa5, 0x0f, 0x6e, 0x7c, 0xdb, 0x52, 0x46, 0xfc,
	0xd8, 0x7f, 0xa8, 0x07, 0x1b, 0x82, 0x61, 0x0f, 0xf5, 0xa8, 0x06, 0x65, 0xd8, 0x43, 0x3d, 0xba,
	0xc1, 0xf8, 0x7f, 0x37, 0x34, 0x37, 0xb7, 0x95, 0x82, 0xb6, 0x9f, 0xcb, 0x28, 0xa9, 0xb8, 0xe0,
	0xc3, 0xc1, 0x96, 0x56, 0xba, 0xa1, 0x79, 0xfe, 0xe9, 0x91, 0x9b, 0x29, 0x21, 0xd8, 0x67, 0x2e,
	0x6c, 0x7e, 0x3b, 0x8b, 0x16, 0xd3, 0xd9, 0x84, 0x27, 0x3f, 0x18, 0xe8, 0x6c, 0x5c, 0xe7, 0x7c,
	0xfb, 0x82, 0x6d, 0xfb, 0x58, 0x1d, 0x4e, 0xa9, 0x60, 0x3f, 0x16, 0x3d, 0xfc, 0x0f, 0xba, 0xa1,
	0x59, 0xc9, 0x4e, 0x93, 0x7a, 0x20, 0xda, 0x1a, 0x07, 0x04, 0x51, 0x29, 0x62, 0x26, 0x11, 0x51,
	0x27, 0x94, 0xb8, 0x3a, 0x5a, 0xc4, 0x9d, 0x23, 0x6f, 0x0a, 0xfe, 0xde, 0x40, 0xc5, 0x18, 0x5e,
	0xdc, 0xa3, 0xe4, 0xc8, 0x33, 0xa6, 0x7d, 0xc9, 0xc3, 0x79, 0xd2, 0x0d, 0xcd, 0x0f, 0xa7, 0x80,
	0x13, 0xf3, 0xba, 0x77, 0xb1, 0x46, 0x53, 0xfb, 0x3b, 0x03, 0xa1, 0x18, 0x56, 0x74, 0x79, 0xf0,
	0x55, 0x7b, 0x8a, 0x86, 0x27, 0x0f, 0xe9, 0x51, 0x37, 0x34, 0x3f, 0x98, 0x1a, 0xd2, 0x84, 0xab,
	0x56, 0xb2, 0xbb, 0xa1, 0xb9, 0x7a, 0xb4, 0xee, 0x49, 0x0c, 0x9e, 0xd9, 0x46, 0xfe, 0x1a, 0x9a,
	0x27, 0x76, 0xde, 0xf9, 0xfc, 0x76, 0x83, 0xa9, 0x66, 0x67, 0xd7, 0x76, 0x45, 0x7b, 0xe3, 0x7f,
	0x5b, 0x7b, 0x1b, 0x0d, 0xb1, 0xae, 0x7b, 0xe1, 0xf5, 0x00, 0xa4, 0xe8, 0x04, 0x2e, 0xc8, 0x0d,
	0xfd, 0x57, 0xdb, 0x6e, 0xa7, 0xbe, 0xa1, 0x27, 0x36, 0xe2, 0x60, 0xdf, 0x18, 0xc6, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x02, 0xdb, 0x12, 0xe8, 0xd6, 0x13, 0x00, 0x00,
}
