---
base_import_path: "github.com/13k/go-steam-resources/protobuf"
input_rel_path: "SteamDatabase/Protobufs"
packages:
  - name: "steam"
    files:
      - "steam/*.proto"
      - "dota2/steamnetworkingsockets_*.proto"
    exclude_files:
      - "steam/*.steamclient.proto"
      - "steam/steamdatagram_*.proto"
      - "steam/steamnetworkingsockets_*.proto"
  - name: "steam/client"
    files:
      - "steam/*.steamclient.proto"
  - name: "steam/steamworks"
    files:
      - "dota2/*.steamworkssdk.proto"
  - name: "dota2"
    files:
      - "dota2/*.proto"
    exclude_files:
      - "dota2/steamdatagram_*.proto"
      - "dota2/steammessages_base.proto"
      - "dota2/steamnetworkingsockets_*.proto"
      - "dota2/*.steamworkssdk.proto"
  - name: "csgo"
    files:
      - "csgo/*.proto"
    exclude_files:
      - "csgo/steamdatagram_*.proto"
      - "csgo/steammessages_base.proto"
      - "csgo/steamnetworkingsockets_*.proto"
  - name: "tf2"
    files:
      - "tf2/*.proto"
    exclude_files:
      - "tf2/steamdatagram_*.proto"
      - "tf2/steamnetworkingsockets_*.proto"
