// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dota_gcmessages_client_watch.proto

package dota2 // import "github.com/13k/go-steam-resources/protobuf/dota2"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMsgWatchGameResponse_WatchGameResult int32

const (
	CMsgWatchGameResponse_PENDING                   CMsgWatchGameResponse_WatchGameResult = 0
	CMsgWatchGameResponse_READY                     CMsgWatchGameResponse_WatchGameResult = 1
	CMsgWatchGameResponse_GAMESERVERNOTFOUND        CMsgWatchGameResponse_WatchGameResult = 2
	CMsgWatchGameResponse_UNAVAILABLE               CMsgWatchGameResponse_WatchGameResult = 3
	CMsgWatchGameResponse_CANCELLED                 CMsgWatchGameResponse_WatchGameResult = 4
	CMsgWatchGameResponse_INCOMPATIBLEVERSION       CMsgWatchGameResponse_WatchGameResult = 5
	CMsgWatchGameResponse_MISSINGLEAGUESUBSCRIPTION CMsgWatchGameResponse_WatchGameResult = 6
	CMsgWatchGameResponse_LOBBYNOTFOUND             CMsgWatchGameResponse_WatchGameResult = 7
)

var CMsgWatchGameResponse_WatchGameResult_name = map[int32]string{
	0: "PENDING",
	1: "READY",
	2: "GAMESERVERNOTFOUND",
	3: "UNAVAILABLE",
	4: "CANCELLED",
	5: "INCOMPATIBLEVERSION",
	6: "MISSINGLEAGUESUBSCRIPTION",
	7: "LOBBYNOTFOUND",
}
var CMsgWatchGameResponse_WatchGameResult_value = map[string]int32{
	"PENDING":                   0,
	"READY":                     1,
	"GAMESERVERNOTFOUND":        2,
	"UNAVAILABLE":               3,
	"CANCELLED":                 4,
	"INCOMPATIBLEVERSION":       5,
	"MISSINGLEAGUESUBSCRIPTION": 6,
	"LOBBYNOTFOUND":             7,
}

func (x CMsgWatchGameResponse_WatchGameResult) Enum() *CMsgWatchGameResponse_WatchGameResult {
	p := new(CMsgWatchGameResponse_WatchGameResult)
	*p = x
	return p
}
func (x CMsgWatchGameResponse_WatchGameResult) String() string {
	return proto.EnumName(CMsgWatchGameResponse_WatchGameResult_name, int32(x))
}
func (x *CMsgWatchGameResponse_WatchGameResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgWatchGameResponse_WatchGameResult_value, data, "CMsgWatchGameResponse_WatchGameResult")
	if err != nil {
		return err
	}
	*x = CMsgWatchGameResponse_WatchGameResult(value)
	return nil
}
func (CMsgWatchGameResponse_WatchGameResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{19, 0}
}

type CSourceTVGameSmall struct {
	ActivateTime               *uint32                      `protobuf:"varint,1,opt,name=activate_time,json=activateTime" json:"activate_time,omitempty"`
	DeactivateTime             *uint32                      `protobuf:"varint,2,opt,name=deactivate_time,json=deactivateTime" json:"deactivate_time,omitempty"`
	ServerSteamId              *uint64                      `protobuf:"varint,3,opt,name=server_steam_id,json=serverSteamId" json:"server_steam_id,omitempty"`
	LobbyId                    *uint64                      `protobuf:"varint,4,opt,name=lobby_id,json=lobbyId" json:"lobby_id,omitempty"`
	LeagueId                   *uint32                      `protobuf:"varint,5,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LobbyType                  *uint32                      `protobuf:"varint,6,opt,name=lobby_type,json=lobbyType" json:"lobby_type,omitempty"`
	GameTime                   *int32                       `protobuf:"varint,7,opt,name=game_time,json=gameTime" json:"game_time,omitempty"`
	Delay                      *uint32                      `protobuf:"varint,8,opt,name=delay" json:"delay,omitempty"`
	Spectators                 *uint32                      `protobuf:"varint,9,opt,name=spectators" json:"spectators,omitempty"`
	GameMode                   *uint32                      `protobuf:"varint,10,opt,name=game_mode,json=gameMode" json:"game_mode,omitempty"`
	AverageMmr                 *uint32                      `protobuf:"varint,11,opt,name=average_mmr,json=averageMmr" json:"average_mmr,omitempty"`
	TeamNameRadiant            *string                      `protobuf:"bytes,15,opt,name=team_name_radiant,json=teamNameRadiant" json:"team_name_radiant,omitempty"`
	TeamNameDire               *string                      `protobuf:"bytes,16,opt,name=team_name_dire,json=teamNameDire" json:"team_name_dire,omitempty"`
	TeamLogoRadiant            *uint64                      `protobuf:"fixed64,24,opt,name=team_logo_radiant,json=teamLogoRadiant" json:"team_logo_radiant,omitempty"`
	TeamLogoDire               *uint64                      `protobuf:"fixed64,25,opt,name=team_logo_dire,json=teamLogoDire" json:"team_logo_dire,omitempty"`
	SortScore                  *uint32                      `protobuf:"varint,17,opt,name=sort_score,json=sortScore" json:"sort_score,omitempty"`
	LastUpdateTime             *float32                     `protobuf:"fixed32,18,opt,name=last_update_time,json=lastUpdateTime" json:"last_update_time,omitempty"`
	RadiantLead                *int32                       `protobuf:"varint,19,opt,name=radiant_lead,json=radiantLead" json:"radiant_lead,omitempty"`
	RadiantScore               *uint32                      `protobuf:"varint,20,opt,name=radiant_score,json=radiantScore" json:"radiant_score,omitempty"`
	DireScore                  *uint32                      `protobuf:"varint,21,opt,name=dire_score,json=direScore" json:"dire_score,omitempty"`
	Players                    []*CSourceTVGameSmall_Player `protobuf:"bytes,22,rep,name=players" json:"players,omitempty"`
	BuildingState              *uint32                      `protobuf:"fixed32,23,opt,name=building_state,json=buildingState" json:"building_state,omitempty"`
	WeekendTourneyTournamentId *uint32                      `protobuf:"varint,26,opt,name=weekend_tourney_tournament_id,json=weekendTourneyTournamentId" json:"weekend_tourney_tournament_id,omitempty"`
	WeekendTourneyDivision     *uint32                      `protobuf:"varint,27,opt,name=weekend_tourney_division,json=weekendTourneyDivision" json:"weekend_tourney_division,omitempty"`
	WeekendTourneySkillLevel   *uint32                      `protobuf:"varint,28,opt,name=weekend_tourney_skill_level,json=weekendTourneySkillLevel" json:"weekend_tourney_skill_level,omitempty"`
	WeekendTourneyBracketRound *uint32                      `protobuf:"varint,29,opt,name=weekend_tourney_bracket_round,json=weekendTourneyBracketRound" json:"weekend_tourney_bracket_round,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                     `json:"-"`
	XXX_unrecognized           []byte                       `json:"-"`
	XXX_sizecache              int32                        `json:"-"`
}

func (m *CSourceTVGameSmall) Reset()         { *m = CSourceTVGameSmall{} }
func (m *CSourceTVGameSmall) String() string { return proto.CompactTextString(m) }
func (*CSourceTVGameSmall) ProtoMessage()    {}
func (*CSourceTVGameSmall) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{0}
}
func (m *CSourceTVGameSmall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSourceTVGameSmall.Unmarshal(m, b)
}
func (m *CSourceTVGameSmall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSourceTVGameSmall.Marshal(b, m, deterministic)
}
func (dst *CSourceTVGameSmall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSourceTVGameSmall.Merge(dst, src)
}
func (m *CSourceTVGameSmall) XXX_Size() int {
	return xxx_messageInfo_CSourceTVGameSmall.Size(m)
}
func (m *CSourceTVGameSmall) XXX_DiscardUnknown() {
	xxx_messageInfo_CSourceTVGameSmall.DiscardUnknown(m)
}

var xxx_messageInfo_CSourceTVGameSmall proto.InternalMessageInfo

func (m *CSourceTVGameSmall) GetActivateTime() uint32 {
	if m != nil && m.ActivateTime != nil {
		return *m.ActivateTime
	}
	return 0
}

func (m *CSourceTVGameSmall) GetDeactivateTime() uint32 {
	if m != nil && m.DeactivateTime != nil {
		return *m.DeactivateTime
	}
	return 0
}

func (m *CSourceTVGameSmall) GetServerSteamId() uint64 {
	if m != nil && m.ServerSteamId != nil {
		return *m.ServerSteamId
	}
	return 0
}

func (m *CSourceTVGameSmall) GetLobbyId() uint64 {
	if m != nil && m.LobbyId != nil {
		return *m.LobbyId
	}
	return 0
}

func (m *CSourceTVGameSmall) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CSourceTVGameSmall) GetLobbyType() uint32 {
	if m != nil && m.LobbyType != nil {
		return *m.LobbyType
	}
	return 0
}

func (m *CSourceTVGameSmall) GetGameTime() int32 {
	if m != nil && m.GameTime != nil {
		return *m.GameTime
	}
	return 0
}

func (m *CSourceTVGameSmall) GetDelay() uint32 {
	if m != nil && m.Delay != nil {
		return *m.Delay
	}
	return 0
}

func (m *CSourceTVGameSmall) GetSpectators() uint32 {
	if m != nil && m.Spectators != nil {
		return *m.Spectators
	}
	return 0
}

func (m *CSourceTVGameSmall) GetGameMode() uint32 {
	if m != nil && m.GameMode != nil {
		return *m.GameMode
	}
	return 0
}

func (m *CSourceTVGameSmall) GetAverageMmr() uint32 {
	if m != nil && m.AverageMmr != nil {
		return *m.AverageMmr
	}
	return 0
}

func (m *CSourceTVGameSmall) GetTeamNameRadiant() string {
	if m != nil && m.TeamNameRadiant != nil {
		return *m.TeamNameRadiant
	}
	return ""
}

func (m *CSourceTVGameSmall) GetTeamNameDire() string {
	if m != nil && m.TeamNameDire != nil {
		return *m.TeamNameDire
	}
	return ""
}

func (m *CSourceTVGameSmall) GetTeamLogoRadiant() uint64 {
	if m != nil && m.TeamLogoRadiant != nil {
		return *m.TeamLogoRadiant
	}
	return 0
}

func (m *CSourceTVGameSmall) GetTeamLogoDire() uint64 {
	if m != nil && m.TeamLogoDire != nil {
		return *m.TeamLogoDire
	}
	return 0
}

func (m *CSourceTVGameSmall) GetSortScore() uint32 {
	if m != nil && m.SortScore != nil {
		return *m.SortScore
	}
	return 0
}

func (m *CSourceTVGameSmall) GetLastUpdateTime() float32 {
	if m != nil && m.LastUpdateTime != nil {
		return *m.LastUpdateTime
	}
	return 0
}

func (m *CSourceTVGameSmall) GetRadiantLead() int32 {
	if m != nil && m.RadiantLead != nil {
		return *m.RadiantLead
	}
	return 0
}

func (m *CSourceTVGameSmall) GetRadiantScore() uint32 {
	if m != nil && m.RadiantScore != nil {
		return *m.RadiantScore
	}
	return 0
}

func (m *CSourceTVGameSmall) GetDireScore() uint32 {
	if m != nil && m.DireScore != nil {
		return *m.DireScore
	}
	return 0
}

func (m *CSourceTVGameSmall) GetPlayers() []*CSourceTVGameSmall_Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *CSourceTVGameSmall) GetBuildingState() uint32 {
	if m != nil && m.BuildingState != nil {
		return *m.BuildingState
	}
	return 0
}

func (m *CSourceTVGameSmall) GetWeekendTourneyTournamentId() uint32 {
	if m != nil && m.WeekendTourneyTournamentId != nil {
		return *m.WeekendTourneyTournamentId
	}
	return 0
}

func (m *CSourceTVGameSmall) GetWeekendTourneyDivision() uint32 {
	if m != nil && m.WeekendTourneyDivision != nil {
		return *m.WeekendTourneyDivision
	}
	return 0
}

func (m *CSourceTVGameSmall) GetWeekendTourneySkillLevel() uint32 {
	if m != nil && m.WeekendTourneySkillLevel != nil {
		return *m.WeekendTourneySkillLevel
	}
	return 0
}

func (m *CSourceTVGameSmall) GetWeekendTourneyBracketRound() uint32 {
	if m != nil && m.WeekendTourneyBracketRound != nil {
		return *m.WeekendTourneyBracketRound
	}
	return 0
}

type CSourceTVGameSmall_Player struct {
	AccountId            *uint32  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	HeroId               *uint32  `protobuf:"varint,2,opt,name=hero_id,json=heroId" json:"hero_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSourceTVGameSmall_Player) Reset()         { *m = CSourceTVGameSmall_Player{} }
func (m *CSourceTVGameSmall_Player) String() string { return proto.CompactTextString(m) }
func (*CSourceTVGameSmall_Player) ProtoMessage()    {}
func (*CSourceTVGameSmall_Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{0, 0}
}
func (m *CSourceTVGameSmall_Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSourceTVGameSmall_Player.Unmarshal(m, b)
}
func (m *CSourceTVGameSmall_Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSourceTVGameSmall_Player.Marshal(b, m, deterministic)
}
func (dst *CSourceTVGameSmall_Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSourceTVGameSmall_Player.Merge(dst, src)
}
func (m *CSourceTVGameSmall_Player) XXX_Size() int {
	return xxx_messageInfo_CSourceTVGameSmall_Player.Size(m)
}
func (m *CSourceTVGameSmall_Player) XXX_DiscardUnknown() {
	xxx_messageInfo_CSourceTVGameSmall_Player.DiscardUnknown(m)
}

var xxx_messageInfo_CSourceTVGameSmall_Player proto.InternalMessageInfo

func (m *CSourceTVGameSmall_Player) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CSourceTVGameSmall_Player) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

type CMsgClientToGCFindTopSourceTVGames struct {
	SearchKey            *string  `protobuf:"bytes,1,opt,name=search_key,json=searchKey" json:"search_key,omitempty"`
	LeagueId             *uint32  `protobuf:"varint,2,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	HeroId               *uint32  `protobuf:"varint,3,opt,name=hero_id,json=heroId" json:"hero_id,omitempty"`
	StartGame            *uint32  `protobuf:"varint,4,opt,name=start_game,json=startGame" json:"start_game,omitempty"`
	GameListIndex        *uint32  `protobuf:"varint,5,opt,name=game_list_index,json=gameListIndex" json:"game_list_index,omitempty"`
	LobbyIds             []uint64 `protobuf:"varint,6,rep,name=lobby_ids,json=lobbyIds" json:"lobby_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCFindTopSourceTVGames) Reset()         { *m = CMsgClientToGCFindTopSourceTVGames{} }
func (m *CMsgClientToGCFindTopSourceTVGames) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCFindTopSourceTVGames) ProtoMessage()    {}
func (*CMsgClientToGCFindTopSourceTVGames) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{1}
}
func (m *CMsgClientToGCFindTopSourceTVGames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCFindTopSourceTVGames.Unmarshal(m, b)
}
func (m *CMsgClientToGCFindTopSourceTVGames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCFindTopSourceTVGames.Marshal(b, m, deterministic)
}
func (dst *CMsgClientToGCFindTopSourceTVGames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCFindTopSourceTVGames.Merge(dst, src)
}
func (m *CMsgClientToGCFindTopSourceTVGames) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCFindTopSourceTVGames.Size(m)
}
func (m *CMsgClientToGCFindTopSourceTVGames) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCFindTopSourceTVGames.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCFindTopSourceTVGames proto.InternalMessageInfo

func (m *CMsgClientToGCFindTopSourceTVGames) GetSearchKey() string {
	if m != nil && m.SearchKey != nil {
		return *m.SearchKey
	}
	return ""
}

func (m *CMsgClientToGCFindTopSourceTVGames) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgClientToGCFindTopSourceTVGames) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *CMsgClientToGCFindTopSourceTVGames) GetStartGame() uint32 {
	if m != nil && m.StartGame != nil {
		return *m.StartGame
	}
	return 0
}

func (m *CMsgClientToGCFindTopSourceTVGames) GetGameListIndex() uint32 {
	if m != nil && m.GameListIndex != nil {
		return *m.GameListIndex
	}
	return 0
}

func (m *CMsgClientToGCFindTopSourceTVGames) GetLobbyIds() []uint64 {
	if m != nil {
		return m.LobbyIds
	}
	return nil
}

type CMsgGCToClientFindTopSourceTVGamesResponse struct {
	SearchKey            *string               `protobuf:"bytes,1,opt,name=search_key,json=searchKey" json:"search_key,omitempty"`
	LeagueId             *uint32               `protobuf:"varint,2,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	HeroId               *uint32               `protobuf:"varint,3,opt,name=hero_id,json=heroId" json:"hero_id,omitempty"`
	StartGame            *uint32               `protobuf:"varint,4,opt,name=start_game,json=startGame" json:"start_game,omitempty"`
	NumGames             *uint32               `protobuf:"varint,5,opt,name=num_games,json=numGames" json:"num_games,omitempty"`
	GameListIndex        *uint32               `protobuf:"varint,6,opt,name=game_list_index,json=gameListIndex" json:"game_list_index,omitempty"`
	GameList             []*CSourceTVGameSmall `protobuf:"bytes,7,rep,name=game_list,json=gameList" json:"game_list,omitempty"`
	SpecificGames        *bool                 `protobuf:"varint,8,opt,name=specific_games,json=specificGames" json:"specific_games,omitempty"`
	BotGame              *CSourceTVGameSmall   `protobuf:"bytes,9,opt,name=bot_game,json=botGame" json:"bot_game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) Reset() {
	*m = CMsgGCToClientFindTopSourceTVGamesResponse{}
}
func (m *CMsgGCToClientFindTopSourceTVGamesResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgGCToClientFindTopSourceTVGamesResponse) ProtoMessage() {}
func (*CMsgGCToClientFindTopSourceTVGamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{2}
}
func (m *CMsgGCToClientFindTopSourceTVGamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientFindTopSourceTVGamesResponse.Unmarshal(m, b)
}
func (m *CMsgGCToClientFindTopSourceTVGamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientFindTopSourceTVGamesResponse.Marshal(b, m, deterministic)
}
func (dst *CMsgGCToClientFindTopSourceTVGamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientFindTopSourceTVGamesResponse.Merge(dst, src)
}
func (m *CMsgGCToClientFindTopSourceTVGamesResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientFindTopSourceTVGamesResponse.Size(m)
}
func (m *CMsgGCToClientFindTopSourceTVGamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientFindTopSourceTVGamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientFindTopSourceTVGamesResponse proto.InternalMessageInfo

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) GetSearchKey() string {
	if m != nil && m.SearchKey != nil {
		return *m.SearchKey
	}
	return ""
}

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) GetStartGame() uint32 {
	if m != nil && m.StartGame != nil {
		return *m.StartGame
	}
	return 0
}

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) GetNumGames() uint32 {
	if m != nil && m.NumGames != nil {
		return *m.NumGames
	}
	return 0
}

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) GetGameListIndex() uint32 {
	if m != nil && m.GameListIndex != nil {
		return *m.GameListIndex
	}
	return 0
}

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) GetGameList() []*CSourceTVGameSmall {
	if m != nil {
		return m.GameList
	}
	return nil
}

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) GetSpecificGames() bool {
	if m != nil && m.SpecificGames != nil {
		return *m.SpecificGames
	}
	return false
}

func (m *CMsgGCToClientFindTopSourceTVGamesResponse) GetBotGame() *CSourceTVGameSmall {
	if m != nil {
		return m.BotGame
	}
	return nil
}

type CMsgGCToClientTopWeekendTourneyGames struct {
	LiveGames            []*CSourceTVGameSmall `protobuf:"bytes,1,rep,name=live_games,json=liveGames" json:"live_games,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CMsgGCToClientTopWeekendTourneyGames) Reset()         { *m = CMsgGCToClientTopWeekendTourneyGames{} }
func (m *CMsgGCToClientTopWeekendTourneyGames) String() string { return proto.CompactTextString(m) }
func (*CMsgGCToClientTopWeekendTourneyGames) ProtoMessage()    {}
func (*CMsgGCToClientTopWeekendTourneyGames) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{3}
}
func (m *CMsgGCToClientTopWeekendTourneyGames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientTopWeekendTourneyGames.Unmarshal(m, b)
}
func (m *CMsgGCToClientTopWeekendTourneyGames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientTopWeekendTourneyGames.Marshal(b, m, deterministic)
}
func (dst *CMsgGCToClientTopWeekendTourneyGames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientTopWeekendTourneyGames.Merge(dst, src)
}
func (m *CMsgGCToClientTopWeekendTourneyGames) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientTopWeekendTourneyGames.Size(m)
}
func (m *CMsgGCToClientTopWeekendTourneyGames) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientTopWeekendTourneyGames.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientTopWeekendTourneyGames proto.InternalMessageInfo

func (m *CMsgGCToClientTopWeekendTourneyGames) GetLiveGames() []*CSourceTVGameSmall {
	if m != nil {
		return m.LiveGames
	}
	return nil
}

type CMsgClientToGCTopMatchesRequest struct {
	HeroId               *uint32  `protobuf:"varint,1,opt,name=hero_id,json=heroId" json:"hero_id,omitempty"`
	PlayerAccountId      *uint32  `protobuf:"varint,2,opt,name=player_account_id,json=playerAccountId" json:"player_account_id,omitempty"`
	TeamId               *uint32  `protobuf:"varint,3,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCTopMatchesRequest) Reset()         { *m = CMsgClientToGCTopMatchesRequest{} }
func (m *CMsgClientToGCTopMatchesRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCTopMatchesRequest) ProtoMessage()    {}
func (*CMsgClientToGCTopMatchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{4}
}
func (m *CMsgClientToGCTopMatchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCTopMatchesRequest.Unmarshal(m, b)
}
func (m *CMsgClientToGCTopMatchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCTopMatchesRequest.Marshal(b, m, deterministic)
}
func (dst *CMsgClientToGCTopMatchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCTopMatchesRequest.Merge(dst, src)
}
func (m *CMsgClientToGCTopMatchesRequest) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCTopMatchesRequest.Size(m)
}
func (m *CMsgClientToGCTopMatchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCTopMatchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCTopMatchesRequest proto.InternalMessageInfo

func (m *CMsgClientToGCTopMatchesRequest) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *CMsgClientToGCTopMatchesRequest) GetPlayerAccountId() uint32 {
	if m != nil && m.PlayerAccountId != nil {
		return *m.PlayerAccountId
	}
	return 0
}

func (m *CMsgClientToGCTopMatchesRequest) GetTeamId() uint32 {
	if m != nil && m.TeamId != nil {
		return *m.TeamId
	}
	return 0
}

type CMsgClientToGCTopLeagueMatchesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCTopLeagueMatchesRequest) Reset()         { *m = CMsgClientToGCTopLeagueMatchesRequest{} }
func (m *CMsgClientToGCTopLeagueMatchesRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCTopLeagueMatchesRequest) ProtoMessage()    {}
func (*CMsgClientToGCTopLeagueMatchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{5}
}
func (m *CMsgClientToGCTopLeagueMatchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCTopLeagueMatchesRequest.Unmarshal(m, b)
}
func (m *CMsgClientToGCTopLeagueMatchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCTopLeagueMatchesRequest.Marshal(b, m, deterministic)
}
func (dst *CMsgClientToGCTopLeagueMatchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCTopLeagueMatchesRequest.Merge(dst, src)
}
func (m *CMsgClientToGCTopLeagueMatchesRequest) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCTopLeagueMatchesRequest.Size(m)
}
func (m *CMsgClientToGCTopLeagueMatchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCTopLeagueMatchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCTopLeagueMatchesRequest proto.InternalMessageInfo

type CMsgClientToGCTopFriendMatchesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCTopFriendMatchesRequest) Reset()         { *m = CMsgClientToGCTopFriendMatchesRequest{} }
func (m *CMsgClientToGCTopFriendMatchesRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCTopFriendMatchesRequest) ProtoMessage()    {}
func (*CMsgClientToGCTopFriendMatchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{6}
}
func (m *CMsgClientToGCTopFriendMatchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCTopFriendMatchesRequest.Unmarshal(m, b)
}
func (m *CMsgClientToGCTopFriendMatchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCTopFriendMatchesRequest.Marshal(b, m, deterministic)
}
func (dst *CMsgClientToGCTopFriendMatchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCTopFriendMatchesRequest.Merge(dst, src)
}
func (m *CMsgClientToGCTopFriendMatchesRequest) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCTopFriendMatchesRequest.Size(m)
}
func (m *CMsgClientToGCTopFriendMatchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCTopFriendMatchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCTopFriendMatchesRequest proto.InternalMessageInfo

type CMsgClientToGCMatchesMinimalRequest struct {
	MatchIds             []uint64 `protobuf:"varint,1,rep,name=match_ids,json=matchIds" json:"match_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCMatchesMinimalRequest) Reset()         { *m = CMsgClientToGCMatchesMinimalRequest{} }
func (m *CMsgClientToGCMatchesMinimalRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCMatchesMinimalRequest) ProtoMessage()    {}
func (*CMsgClientToGCMatchesMinimalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{7}
}
func (m *CMsgClientToGCMatchesMinimalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCMatchesMinimalRequest.Unmarshal(m, b)
}
func (m *CMsgClientToGCMatchesMinimalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCMatchesMinimalRequest.Marshal(b, m, deterministic)
}
func (dst *CMsgClientToGCMatchesMinimalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCMatchesMinimalRequest.Merge(dst, src)
}
func (m *CMsgClientToGCMatchesMinimalRequest) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCMatchesMinimalRequest.Size(m)
}
func (m *CMsgClientToGCMatchesMinimalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCMatchesMinimalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCMatchesMinimalRequest proto.InternalMessageInfo

func (m *CMsgClientToGCMatchesMinimalRequest) GetMatchIds() []uint64 {
	if m != nil {
		return m.MatchIds
	}
	return nil
}

type CMsgClientToGCMatchesMinimalResponse struct {
	Matches              []*CMsgDOTAMatchMinimal `protobuf:"bytes,1,rep,name=matches" json:"matches,omitempty"`
	LastMatch            *bool                   `protobuf:"varint,2,opt,name=last_match,json=lastMatch" json:"last_match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CMsgClientToGCMatchesMinimalResponse) Reset()         { *m = CMsgClientToGCMatchesMinimalResponse{} }
func (m *CMsgClientToGCMatchesMinimalResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCMatchesMinimalResponse) ProtoMessage()    {}
func (*CMsgClientToGCMatchesMinimalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{8}
}
func (m *CMsgClientToGCMatchesMinimalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCMatchesMinimalResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCMatchesMinimalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCMatchesMinimalResponse.Marshal(b, m, deterministic)
}
func (dst *CMsgClientToGCMatchesMinimalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCMatchesMinimalResponse.Merge(dst, src)
}
func (m *CMsgClientToGCMatchesMinimalResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCMatchesMinimalResponse.Size(m)
}
func (m *CMsgClientToGCMatchesMinimalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCMatchesMinimalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCMatchesMinimalResponse proto.InternalMessageInfo

func (m *CMsgClientToGCMatchesMinimalResponse) GetMatches() []*CMsgDOTAMatchMinimal {
	if m != nil {
		return m.Matches
	}
	return nil
}

func (m *CMsgClientToGCMatchesMinimalResponse) GetLastMatch() bool {
	if m != nil && m.LastMatch != nil {
		return *m.LastMatch
	}
	return false
}

type CMsgGCToClientTopLeagueMatchesResponse struct {
	Matches              []*CMsgDOTAMatchMinimal `protobuf:"bytes,2,rep,name=matches" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CMsgGCToClientTopLeagueMatchesResponse) Reset() {
	*m = CMsgGCToClientTopLeagueMatchesResponse{}
}
func (m *CMsgGCToClientTopLeagueMatchesResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgGCToClientTopLeagueMatchesResponse) ProtoMessage()    {}
func (*CMsgGCToClientTopLeagueMatchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{9}
}
func (m *CMsgGCToClientTopLeagueMatchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientTopLeagueMatchesResponse.Unmarshal(m, b)
}
func (m *CMsgGCToClientTopLeagueMatchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientTopLeagueMatchesResponse.Marshal(b, m, deterministic)
}
func (dst *CMsgGCToClientTopLeagueMatchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientTopLeagueMatchesResponse.Merge(dst, src)
}
func (m *CMsgGCToClientTopLeagueMatchesResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientTopLeagueMatchesResponse.Size(m)
}
func (m *CMsgGCToClientTopLeagueMatchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientTopLeagueMatchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientTopLeagueMatchesResponse proto.InternalMessageInfo

func (m *CMsgGCToClientTopLeagueMatchesResponse) GetMatches() []*CMsgDOTAMatchMinimal {
	if m != nil {
		return m.Matches
	}
	return nil
}

type CMsgGCToClientTopFriendMatchesResponse struct {
	Matches              []*CMsgDOTAMatchMinimal `protobuf:"bytes,1,rep,name=matches" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CMsgGCToClientTopFriendMatchesResponse) Reset() {
	*m = CMsgGCToClientTopFriendMatchesResponse{}
}
func (m *CMsgGCToClientTopFriendMatchesResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgGCToClientTopFriendMatchesResponse) ProtoMessage()    {}
func (*CMsgGCToClientTopFriendMatchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{10}
}
func (m *CMsgGCToClientTopFriendMatchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientTopFriendMatchesResponse.Unmarshal(m, b)
}
func (m *CMsgGCToClientTopFriendMatchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientTopFriendMatchesResponse.Marshal(b, m, deterministic)
}
func (dst *CMsgGCToClientTopFriendMatchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientTopFriendMatchesResponse.Merge(dst, src)
}
func (m *CMsgGCToClientTopFriendMatchesResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientTopFriendMatchesResponse.Size(m)
}
func (m *CMsgGCToClientTopFriendMatchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientTopFriendMatchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientTopFriendMatchesResponse proto.InternalMessageInfo

func (m *CMsgGCToClientTopFriendMatchesResponse) GetMatches() []*CMsgDOTAMatchMinimal {
	if m != nil {
		return m.Matches
	}
	return nil
}

type CMsgClientToGCFindTopMatches struct {
	StartGame            *uint32  `protobuf:"varint,1,opt,name=start_game,json=startGame" json:"start_game,omitempty"`
	LeagueId             *uint32  `protobuf:"varint,2,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	HeroId               *uint32  `protobuf:"varint,3,opt,name=hero_id,json=heroId" json:"hero_id,omitempty"`
	FriendId             *uint32  `protobuf:"varint,4,opt,name=friend_id,json=friendId" json:"friend_id,omitempty"`
	FriendList           *bool    `protobuf:"varint,5,opt,name=friend_list,json=friendList" json:"friend_list,omitempty"`
	LeagueList           *bool    `protobuf:"varint,6,opt,name=league_list,json=leagueList" json:"league_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCFindTopMatches) Reset()         { *m = CMsgClientToGCFindTopMatches{} }
func (m *CMsgClientToGCFindTopMatches) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCFindTopMatches) ProtoMessage()    {}
func (*CMsgClientToGCFindTopMatches) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{11}
}
func (m *CMsgClientToGCFindTopMatches) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCFindTopMatches.Unmarshal(m, b)
}
func (m *CMsgClientToGCFindTopMatches) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCFindTopMatches.Marshal(b, m, deterministic)
}
func (dst *CMsgClientToGCFindTopMatches) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCFindTopMatches.Merge(dst, src)
}
func (m *CMsgClientToGCFindTopMatches) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCFindTopMatches.Size(m)
}
func (m *CMsgClientToGCFindTopMatches) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCFindTopMatches.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCFindTopMatches proto.InternalMessageInfo

func (m *CMsgClientToGCFindTopMatches) GetStartGame() uint32 {
	if m != nil && m.StartGame != nil {
		return *m.StartGame
	}
	return 0
}

func (m *CMsgClientToGCFindTopMatches) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgClientToGCFindTopMatches) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *CMsgClientToGCFindTopMatches) GetFriendId() uint32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

func (m *CMsgClientToGCFindTopMatches) GetFriendList() bool {
	if m != nil && m.FriendList != nil {
		return *m.FriendList
	}
	return false
}

func (m *CMsgClientToGCFindTopMatches) GetLeagueList() bool {
	if m != nil && m.LeagueList != nil {
		return *m.LeagueList
	}
	return false
}

type CMsgGCToClientFindTopLeagueMatchesResponse struct {
	StartGame            *uint32          `protobuf:"varint,1,opt,name=start_game,json=startGame" json:"start_game,omitempty"`
	LeagueId             *uint32          `protobuf:"varint,2,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	HeroId               *uint32          `protobuf:"varint,3,opt,name=hero_id,json=heroId" json:"hero_id,omitempty"`
	MatchIds             []uint32         `protobuf:"varint,4,rep,name=match_ids,json=matchIds" json:"match_ids,omitempty"`
	Matches              []*CMsgDOTAMatch `protobuf:"bytes,5,rep,name=matches" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CMsgGCToClientFindTopLeagueMatchesResponse) Reset() {
	*m = CMsgGCToClientFindTopLeagueMatchesResponse{}
}
func (m *CMsgGCToClientFindTopLeagueMatchesResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgGCToClientFindTopLeagueMatchesResponse) ProtoMessage() {}
func (*CMsgGCToClientFindTopLeagueMatchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{12}
}
func (m *CMsgGCToClientFindTopLeagueMatchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientFindTopLeagueMatchesResponse.Unmarshal(m, b)
}
func (m *CMsgGCToClientFindTopLeagueMatchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientFindTopLeagueMatchesResponse.Marshal(b, m, deterministic)
}
func (dst *CMsgGCToClientFindTopLeagueMatchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientFindTopLeagueMatchesResponse.Merge(dst, src)
}
func (m *CMsgGCToClientFindTopLeagueMatchesResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientFindTopLeagueMatchesResponse.Size(m)
}
func (m *CMsgGCToClientFindTopLeagueMatchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientFindTopLeagueMatchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientFindTopLeagueMatchesResponse proto.InternalMessageInfo

func (m *CMsgGCToClientFindTopLeagueMatchesResponse) GetStartGame() uint32 {
	if m != nil && m.StartGame != nil {
		return *m.StartGame
	}
	return 0
}

func (m *CMsgGCToClientFindTopLeagueMatchesResponse) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgGCToClientFindTopLeagueMatchesResponse) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *CMsgGCToClientFindTopLeagueMatchesResponse) GetMatchIds() []uint32 {
	if m != nil {
		return m.MatchIds
	}
	return nil
}

func (m *CMsgGCToClientFindTopLeagueMatchesResponse) GetMatches() []*CMsgDOTAMatch {
	if m != nil {
		return m.Matches
	}
	return nil
}

type CMsgSpectateFriendGame struct {
	SteamId              *uint64  `protobuf:"fixed64,1,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgSpectateFriendGame) Reset()         { *m = CMsgSpectateFriendGame{} }
func (m *CMsgSpectateFriendGame) String() string { return proto.CompactTextString(m) }
func (*CMsgSpectateFriendGame) ProtoMessage()    {}
func (*CMsgSpectateFriendGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{13}
}
func (m *CMsgSpectateFriendGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgSpectateFriendGame.Unmarshal(m, b)
}
func (m *CMsgSpectateFriendGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgSpectateFriendGame.Marshal(b, m, deterministic)
}
func (dst *CMsgSpectateFriendGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgSpectateFriendGame.Merge(dst, src)
}
func (m *CMsgSpectateFriendGame) XXX_Size() int {
	return xxx_messageInfo_CMsgSpectateFriendGame.Size(m)
}
func (m *CMsgSpectateFriendGame) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgSpectateFriendGame.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgSpectateFriendGame proto.InternalMessageInfo

func (m *CMsgSpectateFriendGame) GetSteamId() uint64 {
	if m != nil && m.SteamId != nil {
		return *m.SteamId
	}
	return 0
}

type CMsgSpectateFriendGameResponse struct {
	ServerSteamid        *uint64  `protobuf:"fixed64,4,opt,name=server_steamid,json=serverSteamid" json:"server_steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgSpectateFriendGameResponse) Reset()         { *m = CMsgSpectateFriendGameResponse{} }
func (m *CMsgSpectateFriendGameResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgSpectateFriendGameResponse) ProtoMessage()    {}
func (*CMsgSpectateFriendGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{14}
}
func (m *CMsgSpectateFriendGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgSpectateFriendGameResponse.Unmarshal(m, b)
}
func (m *CMsgSpectateFriendGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgSpectateFriendGameResponse.Marshal(b, m, deterministic)
}
func (dst *CMsgSpectateFriendGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgSpectateFriendGameResponse.Merge(dst, src)
}
func (m *CMsgSpectateFriendGameResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgSpectateFriendGameResponse.Size(m)
}
func (m *CMsgSpectateFriendGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgSpectateFriendGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgSpectateFriendGameResponse proto.InternalMessageInfo

func (m *CMsgSpectateFriendGameResponse) GetServerSteamid() uint64 {
	if m != nil && m.ServerSteamid != nil {
		return *m.ServerSteamid
	}
	return 0
}

type CMsgDOTAMatchMinimal struct {
	MatchId              *uint64                        `protobuf:"varint,1,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
	StartTime            *uint32                        `protobuf:"fixed32,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	Duration             *uint32                        `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
	GameMode             *DOTA_GameMode                 `protobuf:"varint,4,opt,name=game_mode,json=gameMode,enum=DOTA_GameMode,def=0" json:"game_mode,omitempty"`
	Players              []*CMsgDOTAMatchMinimal_Player `protobuf:"bytes,6,rep,name=players" json:"players,omitempty"`
	Tourney              *CMsgDOTAMatchMinimal_Tourney  `protobuf:"bytes,7,opt,name=tourney" json:"tourney,omitempty"`
	MatchOutcome         *EMatchOutcome                 `protobuf:"varint,8,opt,name=match_outcome,json=matchOutcome,enum=EMatchOutcome,def=0" json:"match_outcome,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CMsgDOTAMatchMinimal) Reset()         { *m = CMsgDOTAMatchMinimal{} }
func (m *CMsgDOTAMatchMinimal) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAMatchMinimal) ProtoMessage()    {}
func (*CMsgDOTAMatchMinimal) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{15}
}
func (m *CMsgDOTAMatchMinimal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAMatchMinimal.Unmarshal(m, b)
}
func (m *CMsgDOTAMatchMinimal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAMatchMinimal.Marshal(b, m, deterministic)
}
func (dst *CMsgDOTAMatchMinimal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAMatchMinimal.Merge(dst, src)
}
func (m *CMsgDOTAMatchMinimal) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAMatchMinimal.Size(m)
}
func (m *CMsgDOTAMatchMinimal) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAMatchMinimal.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAMatchMinimal proto.InternalMessageInfo

const Default_CMsgDOTAMatchMinimal_GameMode DOTA_GameMode = DOTA_GameMode_DOTA_GAMEMODE_NONE
const Default_CMsgDOTAMatchMinimal_MatchOutcome EMatchOutcome = EMatchOutcome_k_EMatchOutcome_Unknown

func (m *CMsgDOTAMatchMinimal) GetMatchId() uint64 {
	if m != nil && m.MatchId != nil {
		return *m.MatchId
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal) GetStartTime() uint32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal) GetDuration() uint32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal) GetGameMode() DOTA_GameMode {
	if m != nil && m.GameMode != nil {
		return *m.GameMode
	}
	return Default_CMsgDOTAMatchMinimal_GameMode
}

func (m *CMsgDOTAMatchMinimal) GetPlayers() []*CMsgDOTAMatchMinimal_Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *CMsgDOTAMatchMinimal) GetTourney() *CMsgDOTAMatchMinimal_Tourney {
	if m != nil {
		return m.Tourney
	}
	return nil
}

func (m *CMsgDOTAMatchMinimal) GetMatchOutcome() EMatchOutcome {
	if m != nil && m.MatchOutcome != nil {
		return *m.MatchOutcome
	}
	return Default_CMsgDOTAMatchMinimal_MatchOutcome
}

type CMsgDOTAMatchMinimal_Player struct {
	AccountId            *uint32  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	HeroId               *uint32  `protobuf:"varint,2,opt,name=hero_id,json=heroId" json:"hero_id,omitempty"`
	Kills                *uint32  `protobuf:"varint,3,opt,name=kills" json:"kills,omitempty"`
	Deaths               *uint32  `protobuf:"varint,4,opt,name=deaths" json:"deaths,omitempty"`
	Assists              *uint32  `protobuf:"varint,5,opt,name=assists" json:"assists,omitempty"`
	Items                []uint32 `protobuf:"varint,6,rep,name=items" json:"items,omitempty"`
	PlayerSlot           *uint32  `protobuf:"varint,7,opt,name=player_slot,json=playerSlot" json:"player_slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAMatchMinimal_Player) Reset()         { *m = CMsgDOTAMatchMinimal_Player{} }
func (m *CMsgDOTAMatchMinimal_Player) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAMatchMinimal_Player) ProtoMessage()    {}
func (*CMsgDOTAMatchMinimal_Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{15, 0}
}
func (m *CMsgDOTAMatchMinimal_Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAMatchMinimal_Player.Unmarshal(m, b)
}
func (m *CMsgDOTAMatchMinimal_Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAMatchMinimal_Player.Marshal(b, m, deterministic)
}
func (dst *CMsgDOTAMatchMinimal_Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAMatchMinimal_Player.Merge(dst, src)
}
func (m *CMsgDOTAMatchMinimal_Player) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAMatchMinimal_Player.Size(m)
}
func (m *CMsgDOTAMatchMinimal_Player) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAMatchMinimal_Player.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAMatchMinimal_Player proto.InternalMessageInfo

func (m *CMsgDOTAMatchMinimal_Player) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Player) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Player) GetKills() uint32 {
	if m != nil && m.Kills != nil {
		return *m.Kills
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Player) GetDeaths() uint32 {
	if m != nil && m.Deaths != nil {
		return *m.Deaths
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Player) GetAssists() uint32 {
	if m != nil && m.Assists != nil {
		return *m.Assists
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Player) GetItems() []uint32 {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *CMsgDOTAMatchMinimal_Player) GetPlayerSlot() uint32 {
	if m != nil && m.PlayerSlot != nil {
		return *m.PlayerSlot
	}
	return 0
}

type CMsgDOTAMatchMinimal_Tourney struct {
	LeagueId                     *uint32  `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	SeriesType                   *uint32  `protobuf:"varint,8,opt,name=series_type,json=seriesType" json:"series_type,omitempty"`
	SeriesGame                   *uint32  `protobuf:"varint,9,opt,name=series_game,json=seriesGame" json:"series_game,omitempty"`
	WeekendTourneyTournamentId   *uint32  `protobuf:"varint,10,opt,name=weekend_tourney_tournament_id,json=weekendTourneyTournamentId" json:"weekend_tourney_tournament_id,omitempty"`
	WeekendTourneySeasonTrophyId *uint32  `protobuf:"varint,11,opt,name=weekend_tourney_season_trophy_id,json=weekendTourneySeasonTrophyId" json:"weekend_tourney_season_trophy_id,omitempty"`
	WeekendTourneyDivision       *uint32  `protobuf:"varint,12,opt,name=weekend_tourney_division,json=weekendTourneyDivision" json:"weekend_tourney_division,omitempty"`
	WeekendTourneySkillLevel     *uint32  `protobuf:"varint,13,opt,name=weekend_tourney_skill_level,json=weekendTourneySkillLevel" json:"weekend_tourney_skill_level,omitempty"`
	RadiantTeamId                *uint32  `protobuf:"varint,2,opt,name=radiant_team_id,json=radiantTeamId" json:"radiant_team_id,omitempty"`
	RadiantTeamName              *string  `protobuf:"bytes,3,opt,name=radiant_team_name,json=radiantTeamName" json:"radiant_team_name,omitempty"`
	RadiantTeamLogo              *uint64  `protobuf:"fixed64,4,opt,name=radiant_team_logo,json=radiantTeamLogo" json:"radiant_team_logo,omitempty"`
	DireTeamId                   *uint32  `protobuf:"varint,5,opt,name=dire_team_id,json=direTeamId" json:"dire_team_id,omitempty"`
	DireTeamName                 *string  `protobuf:"bytes,6,opt,name=dire_team_name,json=direTeamName" json:"dire_team_name,omitempty"`
	DireTeamLogo                 *uint64  `protobuf:"fixed64,7,opt,name=dire_team_logo,json=direTeamLogo" json:"dire_team_logo,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *CMsgDOTAMatchMinimal_Tourney) Reset()         { *m = CMsgDOTAMatchMinimal_Tourney{} }
func (m *CMsgDOTAMatchMinimal_Tourney) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAMatchMinimal_Tourney) ProtoMessage()    {}
func (*CMsgDOTAMatchMinimal_Tourney) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{15, 1}
}
func (m *CMsgDOTAMatchMinimal_Tourney) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAMatchMinimal_Tourney.Unmarshal(m, b)
}
func (m *CMsgDOTAMatchMinimal_Tourney) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAMatchMinimal_Tourney.Marshal(b, m, deterministic)
}
func (dst *CMsgDOTAMatchMinimal_Tourney) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAMatchMinimal_Tourney.Merge(dst, src)
}
func (m *CMsgDOTAMatchMinimal_Tourney) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAMatchMinimal_Tourney.Size(m)
}
func (m *CMsgDOTAMatchMinimal_Tourney) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAMatchMinimal_Tourney.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAMatchMinimal_Tourney proto.InternalMessageInfo

func (m *CMsgDOTAMatchMinimal_Tourney) GetLeagueId() uint32 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetSeriesType() uint32 {
	if m != nil && m.SeriesType != nil {
		return *m.SeriesType
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetSeriesGame() uint32 {
	if m != nil && m.SeriesGame != nil {
		return *m.SeriesGame
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetWeekendTourneyTournamentId() uint32 {
	if m != nil && m.WeekendTourneyTournamentId != nil {
		return *m.WeekendTourneyTournamentId
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetWeekendTourneySeasonTrophyId() uint32 {
	if m != nil && m.WeekendTourneySeasonTrophyId != nil {
		return *m.WeekendTourneySeasonTrophyId
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetWeekendTourneyDivision() uint32 {
	if m != nil && m.WeekendTourneyDivision != nil {
		return *m.WeekendTourneyDivision
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetWeekendTourneySkillLevel() uint32 {
	if m != nil && m.WeekendTourneySkillLevel != nil {
		return *m.WeekendTourneySkillLevel
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetRadiantTeamId() uint32 {
	if m != nil && m.RadiantTeamId != nil {
		return *m.RadiantTeamId
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetRadiantTeamName() string {
	if m != nil && m.RadiantTeamName != nil {
		return *m.RadiantTeamName
	}
	return ""
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetRadiantTeamLogo() uint64 {
	if m != nil && m.RadiantTeamLogo != nil {
		return *m.RadiantTeamLogo
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetDireTeamId() uint32 {
	if m != nil && m.DireTeamId != nil {
		return *m.DireTeamId
	}
	return 0
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetDireTeamName() string {
	if m != nil && m.DireTeamName != nil {
		return *m.DireTeamName
	}
	return ""
}

func (m *CMsgDOTAMatchMinimal_Tourney) GetDireTeamLogo() uint64 {
	if m != nil && m.DireTeamLogo != nil {
		return *m.DireTeamLogo
	}
	return 0
}

type CDOTAReplayDownloadInfo struct {
	Match                *CMsgDOTAMatchMinimal `protobuf:"bytes,1,opt,name=match" json:"match,omitempty"`
	Title                *string               `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description          *string               `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Size                 *uint32               `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Tags                 []string              `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	ExistsOnDisk         *bool                 `protobuf:"varint,6,opt,name=exists_on_disk,json=existsOnDisk" json:"exists_on_disk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CDOTAReplayDownloadInfo) Reset()         { *m = CDOTAReplayDownloadInfo{} }
func (m *CDOTAReplayDownloadInfo) String() string { return proto.CompactTextString(m) }
func (*CDOTAReplayDownloadInfo) ProtoMessage()    {}
func (*CDOTAReplayDownloadInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{16}
}
func (m *CDOTAReplayDownloadInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDOTAReplayDownloadInfo.Unmarshal(m, b)
}
func (m *CDOTAReplayDownloadInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDOTAReplayDownloadInfo.Marshal(b, m, deterministic)
}
func (dst *CDOTAReplayDownloadInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDOTAReplayDownloadInfo.Merge(dst, src)
}
func (m *CDOTAReplayDownloadInfo) XXX_Size() int {
	return xxx_messageInfo_CDOTAReplayDownloadInfo.Size(m)
}
func (m *CDOTAReplayDownloadInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CDOTAReplayDownloadInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CDOTAReplayDownloadInfo proto.InternalMessageInfo

func (m *CDOTAReplayDownloadInfo) GetMatch() *CMsgDOTAMatchMinimal {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *CDOTAReplayDownloadInfo) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *CDOTAReplayDownloadInfo) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *CDOTAReplayDownloadInfo) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *CDOTAReplayDownloadInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CDOTAReplayDownloadInfo) GetExistsOnDisk() bool {
	if m != nil && m.ExistsOnDisk != nil {
		return *m.ExistsOnDisk
	}
	return false
}

type CDOTAReplayDownloadInfo_Highlight struct {
	Timestamp            *uint32  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Description          *string  `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDOTAReplayDownloadInfo_Highlight) Reset()         { *m = CDOTAReplayDownloadInfo_Highlight{} }
func (m *CDOTAReplayDownloadInfo_Highlight) String() string { return proto.CompactTextString(m) }
func (*CDOTAReplayDownloadInfo_Highlight) ProtoMessage()    {}
func (*CDOTAReplayDownloadInfo_Highlight) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{16, 0}
}
func (m *CDOTAReplayDownloadInfo_Highlight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDOTAReplayDownloadInfo_Highlight.Unmarshal(m, b)
}
func (m *CDOTAReplayDownloadInfo_Highlight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDOTAReplayDownloadInfo_Highlight.Marshal(b, m, deterministic)
}
func (dst *CDOTAReplayDownloadInfo_Highlight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDOTAReplayDownloadInfo_Highlight.Merge(dst, src)
}
func (m *CDOTAReplayDownloadInfo_Highlight) XXX_Size() int {
	return xxx_messageInfo_CDOTAReplayDownloadInfo_Highlight.Size(m)
}
func (m *CDOTAReplayDownloadInfo_Highlight) XXX_DiscardUnknown() {
	xxx_messageInfo_CDOTAReplayDownloadInfo_Highlight.DiscardUnknown(m)
}

var xxx_messageInfo_CDOTAReplayDownloadInfo_Highlight proto.InternalMessageInfo

func (m *CDOTAReplayDownloadInfo_Highlight) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *CDOTAReplayDownloadInfo_Highlight) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type CMsgWatchGame struct {
	ServerSteamid        *uint64  `protobuf:"fixed64,1,opt,name=server_steamid,json=serverSteamid" json:"server_steamid,omitempty"`
	ClientVersion        *uint32  `protobuf:"varint,2,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	WatchServerSteamid   *uint64  `protobuf:"fixed64,3,opt,name=watch_server_steamid,json=watchServerSteamid" json:"watch_server_steamid,omitempty"`
	LobbyId              *uint64  `protobuf:"varint,4,opt,name=lobby_id,json=lobbyId" json:"lobby_id,omitempty"`
	Regions              []uint32 `protobuf:"varint,5,rep,name=regions" json:"regions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgWatchGame) Reset()         { *m = CMsgWatchGame{} }
func (m *CMsgWatchGame) String() string { return proto.CompactTextString(m) }
func (*CMsgWatchGame) ProtoMessage()    {}
func (*CMsgWatchGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{17}
}
func (m *CMsgWatchGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgWatchGame.Unmarshal(m, b)
}
func (m *CMsgWatchGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgWatchGame.Marshal(b, m, deterministic)
}
func (dst *CMsgWatchGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgWatchGame.Merge(dst, src)
}
func (m *CMsgWatchGame) XXX_Size() int {
	return xxx_messageInfo_CMsgWatchGame.Size(m)
}
func (m *CMsgWatchGame) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgWatchGame.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgWatchGame proto.InternalMessageInfo

func (m *CMsgWatchGame) GetServerSteamid() uint64 {
	if m != nil && m.ServerSteamid != nil {
		return *m.ServerSteamid
	}
	return 0
}

func (m *CMsgWatchGame) GetClientVersion() uint32 {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return 0
}

func (m *CMsgWatchGame) GetWatchServerSteamid() uint64 {
	if m != nil && m.WatchServerSteamid != nil {
		return *m.WatchServerSteamid
	}
	return 0
}

func (m *CMsgWatchGame) GetLobbyId() uint64 {
	if m != nil && m.LobbyId != nil {
		return *m.LobbyId
	}
	return 0
}

func (m *CMsgWatchGame) GetRegions() []uint32 {
	if m != nil {
		return m.Regions
	}
	return nil
}

type CMsgCancelWatchGame struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgCancelWatchGame) Reset()         { *m = CMsgCancelWatchGame{} }
func (m *CMsgCancelWatchGame) String() string { return proto.CompactTextString(m) }
func (*CMsgCancelWatchGame) ProtoMessage()    {}
func (*CMsgCancelWatchGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{18}
}
func (m *CMsgCancelWatchGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCancelWatchGame.Unmarshal(m, b)
}
func (m *CMsgCancelWatchGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCancelWatchGame.Marshal(b, m, deterministic)
}
func (dst *CMsgCancelWatchGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCancelWatchGame.Merge(dst, src)
}
func (m *CMsgCancelWatchGame) XXX_Size() int {
	return xxx_messageInfo_CMsgCancelWatchGame.Size(m)
}
func (m *CMsgCancelWatchGame) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCancelWatchGame.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCancelWatchGame proto.InternalMessageInfo

type CMsgWatchGameResponse struct {
	WatchGameResult         *CMsgWatchGameResponse_WatchGameResult `protobuf:"varint,1,opt,name=watch_game_result,json=watchGameResult,enum=CMsgWatchGameResponse_WatchGameResult,def=0" json:"watch_game_result,omitempty"`
	SourceTvPublicAddr      *uint32                                `protobuf:"varint,2,opt,name=source_tv_public_addr,json=sourceTvPublicAddr" json:"source_tv_public_addr,omitempty"`
	SourceTvPrivateAddr     *uint32                                `protobuf:"varint,3,opt,name=source_tv_private_addr,json=sourceTvPrivateAddr" json:"source_tv_private_addr,omitempty"`
	SourceTvPort            *uint32                                `protobuf:"varint,4,opt,name=source_tv_port,json=sourceTvPort" json:"source_tv_port,omitempty"`
	GameServerSteamid       *uint64                                `protobuf:"fixed64,5,opt,name=game_server_steamid,json=gameServerSteamid" json:"game_server_steamid,omitempty"`
	WatchServerSteamid      *uint64                                `protobuf:"fixed64,6,opt,name=watch_server_steamid,json=watchServerSteamid" json:"watch_server_steamid,omitempty"`
	WatchTvUniqueSecretCode *uint64                                `protobuf:"fixed64,7,opt,name=watch_tv_unique_secret_code,json=watchTvUniqueSecretCode" json:"watch_tv_unique_secret_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                               `json:"-"`
	XXX_unrecognized        []byte                                 `json:"-"`
	XXX_sizecache           int32                                  `json:"-"`
}

func (m *CMsgWatchGameResponse) Reset()         { *m = CMsgWatchGameResponse{} }
func (m *CMsgWatchGameResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgWatchGameResponse) ProtoMessage()    {}
func (*CMsgWatchGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{19}
}
func (m *CMsgWatchGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgWatchGameResponse.Unmarshal(m, b)
}
func (m *CMsgWatchGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgWatchGameResponse.Marshal(b, m, deterministic)
}
func (dst *CMsgWatchGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgWatchGameResponse.Merge(dst, src)
}
func (m *CMsgWatchGameResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgWatchGameResponse.Size(m)
}
func (m *CMsgWatchGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgWatchGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgWatchGameResponse proto.InternalMessageInfo

const Default_CMsgWatchGameResponse_WatchGameResult CMsgWatchGameResponse_WatchGameResult = CMsgWatchGameResponse_PENDING

func (m *CMsgWatchGameResponse) GetWatchGameResult() CMsgWatchGameResponse_WatchGameResult {
	if m != nil && m.WatchGameResult != nil {
		return *m.WatchGameResult
	}
	return Default_CMsgWatchGameResponse_WatchGameResult
}

func (m *CMsgWatchGameResponse) GetSourceTvPublicAddr() uint32 {
	if m != nil && m.SourceTvPublicAddr != nil {
		return *m.SourceTvPublicAddr
	}
	return 0
}

func (m *CMsgWatchGameResponse) GetSourceTvPrivateAddr() uint32 {
	if m != nil && m.SourceTvPrivateAddr != nil {
		return *m.SourceTvPrivateAddr
	}
	return 0
}

func (m *CMsgWatchGameResponse) GetSourceTvPort() uint32 {
	if m != nil && m.SourceTvPort != nil {
		return *m.SourceTvPort
	}
	return 0
}

func (m *CMsgWatchGameResponse) GetGameServerSteamid() uint64 {
	if m != nil && m.GameServerSteamid != nil {
		return *m.GameServerSteamid
	}
	return 0
}

func (m *CMsgWatchGameResponse) GetWatchServerSteamid() uint64 {
	if m != nil && m.WatchServerSteamid != nil {
		return *m.WatchServerSteamid
	}
	return 0
}

func (m *CMsgWatchGameResponse) GetWatchTvUniqueSecretCode() uint64 {
	if m != nil && m.WatchTvUniqueSecretCode != nil {
		return *m.WatchTvUniqueSecretCode
	}
	return 0
}

type CMsgPartyLeaderWatchGamePrompt struct {
	GameServerSteamid    *uint64  `protobuf:"fixed64,5,opt,name=game_server_steamid,json=gameServerSteamid" json:"game_server_steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgPartyLeaderWatchGamePrompt) Reset()         { *m = CMsgPartyLeaderWatchGamePrompt{} }
func (m *CMsgPartyLeaderWatchGamePrompt) String() string { return proto.CompactTextString(m) }
func (*CMsgPartyLeaderWatchGamePrompt) ProtoMessage()    {}
func (*CMsgPartyLeaderWatchGamePrompt) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{20}
}
func (m *CMsgPartyLeaderWatchGamePrompt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgPartyLeaderWatchGamePrompt.Unmarshal(m, b)
}
func (m *CMsgPartyLeaderWatchGamePrompt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgPartyLeaderWatchGamePrompt.Marshal(b, m, deterministic)
}
func (dst *CMsgPartyLeaderWatchGamePrompt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgPartyLeaderWatchGamePrompt.Merge(dst, src)
}
func (m *CMsgPartyLeaderWatchGamePrompt) XXX_Size() int {
	return xxx_messageInfo_CMsgPartyLeaderWatchGamePrompt.Size(m)
}
func (m *CMsgPartyLeaderWatchGamePrompt) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgPartyLeaderWatchGamePrompt.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgPartyLeaderWatchGamePrompt proto.InternalMessageInfo

func (m *CMsgPartyLeaderWatchGamePrompt) GetGameServerSteamid() uint64 {
	if m != nil && m.GameServerSteamid != nil {
		return *m.GameServerSteamid
	}
	return 0
}

type CDOTABroadcasterInfo struct {
	AccountId                  *uint32  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	ServerSteamId              *uint64  `protobuf:"fixed64,2,opt,name=server_steam_id,json=serverSteamId" json:"server_steam_id,omitempty"`
	Live                       *bool    `protobuf:"varint,3,opt,name=live" json:"live,omitempty"`
	TeamNameRadiant            *string  `protobuf:"bytes,4,opt,name=team_name_radiant,json=teamNameRadiant" json:"team_name_radiant,omitempty"`
	TeamNameDire               *string  `protobuf:"bytes,5,opt,name=team_name_dire,json=teamNameDire" json:"team_name_dire,omitempty"`
	StageName                  *string  `protobuf:"bytes,6,opt,name=stage_name,json=stageName" json:"stage_name,omitempty"`
	SeriesGame                 *uint32  `protobuf:"varint,7,opt,name=series_game,json=seriesGame" json:"series_game,omitempty"`
	SeriesType                 *uint32  `protobuf:"varint,8,opt,name=series_type,json=seriesType" json:"series_type,omitempty"`
	UpcomingBroadcastTimestamp *uint32  `protobuf:"varint,9,opt,name=upcoming_broadcast_timestamp,json=upcomingBroadcastTimestamp" json:"upcoming_broadcast_timestamp,omitempty"`
	AllowLiveVideo             *bool    `protobuf:"varint,10,opt,name=allow_live_video,json=allowLiveVideo" json:"allow_live_video,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *CDOTABroadcasterInfo) Reset()         { *m = CDOTABroadcasterInfo{} }
func (m *CDOTABroadcasterInfo) String() string { return proto.CompactTextString(m) }
func (*CDOTABroadcasterInfo) ProtoMessage()    {}
func (*CDOTABroadcasterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099, []int{21}
}
func (m *CDOTABroadcasterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDOTABroadcasterInfo.Unmarshal(m, b)
}
func (m *CDOTABroadcasterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDOTABroadcasterInfo.Marshal(b, m, deterministic)
}
func (dst *CDOTABroadcasterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDOTABroadcasterInfo.Merge(dst, src)
}
func (m *CDOTABroadcasterInfo) XXX_Size() int {
	return xxx_messageInfo_CDOTABroadcasterInfo.Size(m)
}
func (m *CDOTABroadcasterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CDOTABroadcasterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CDOTABroadcasterInfo proto.InternalMessageInfo

func (m *CDOTABroadcasterInfo) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CDOTABroadcasterInfo) GetServerSteamId() uint64 {
	if m != nil && m.ServerSteamId != nil {
		return *m.ServerSteamId
	}
	return 0
}

func (m *CDOTABroadcasterInfo) GetLive() bool {
	if m != nil && m.Live != nil {
		return *m.Live
	}
	return false
}

func (m *CDOTABroadcasterInfo) GetTeamNameRadiant() string {
	if m != nil && m.TeamNameRadiant != nil {
		return *m.TeamNameRadiant
	}
	return ""
}

func (m *CDOTABroadcasterInfo) GetTeamNameDire() string {
	if m != nil && m.TeamNameDire != nil {
		return *m.TeamNameDire
	}
	return ""
}

func (m *CDOTABroadcasterInfo) GetStageName() string {
	if m != nil && m.StageName != nil {
		return *m.StageName
	}
	return ""
}

func (m *CDOTABroadcasterInfo) GetSeriesGame() uint32 {
	if m != nil && m.SeriesGame != nil {
		return *m.SeriesGame
	}
	return 0
}

func (m *CDOTABroadcasterInfo) GetSeriesType() uint32 {
	if m != nil && m.SeriesType != nil {
		return *m.SeriesType
	}
	return 0
}

func (m *CDOTABroadcasterInfo) GetUpcomingBroadcastTimestamp() uint32 {
	if m != nil && m.UpcomingBroadcastTimestamp != nil {
		return *m.UpcomingBroadcastTimestamp
	}
	return 0
}

func (m *CDOTABroadcasterInfo) GetAllowLiveVideo() bool {
	if m != nil && m.AllowLiveVideo != nil {
		return *m.AllowLiveVideo
	}
	return false
}

func init() {
	proto.RegisterType((*CSourceTVGameSmall)(nil), "CSourceTVGameSmall")
	proto.RegisterType((*CSourceTVGameSmall_Player)(nil), "CSourceTVGameSmall.Player")
	proto.RegisterType((*CMsgClientToGCFindTopSourceTVGames)(nil), "CMsgClientToGCFindTopSourceTVGames")
	proto.RegisterType((*CMsgGCToClientFindTopSourceTVGamesResponse)(nil), "CMsgGCToClientFindTopSourceTVGamesResponse")
	proto.RegisterType((*CMsgGCToClientTopWeekendTourneyGames)(nil), "CMsgGCToClientTopWeekendTourneyGames")
	proto.RegisterType((*CMsgClientToGCTopMatchesRequest)(nil), "CMsgClientToGCTopMatchesRequest")
	proto.RegisterType((*CMsgClientToGCTopLeagueMatchesRequest)(nil), "CMsgClientToGCTopLeagueMatchesRequest")
	proto.RegisterType((*CMsgClientToGCTopFriendMatchesRequest)(nil), "CMsgClientToGCTopFriendMatchesRequest")
	proto.RegisterType((*CMsgClientToGCMatchesMinimalRequest)(nil), "CMsgClientToGCMatchesMinimalRequest")
	proto.RegisterType((*CMsgClientToGCMatchesMinimalResponse)(nil), "CMsgClientToGCMatchesMinimalResponse")
	proto.RegisterType((*CMsgGCToClientTopLeagueMatchesResponse)(nil), "CMsgGCToClientTopLeagueMatchesResponse")
	proto.RegisterType((*CMsgGCToClientTopFriendMatchesResponse)(nil), "CMsgGCToClientTopFriendMatchesResponse")
	proto.RegisterType((*CMsgClientToGCFindTopMatches)(nil), "CMsgClientToGCFindTopMatches")
	proto.RegisterType((*CMsgGCToClientFindTopLeagueMatchesResponse)(nil), "CMsgGCToClientFindTopLeagueMatchesResponse")
	proto.RegisterType((*CMsgSpectateFriendGame)(nil), "CMsgSpectateFriendGame")
	proto.RegisterType((*CMsgSpectateFriendGameResponse)(nil), "CMsgSpectateFriendGameResponse")
	proto.RegisterType((*CMsgDOTAMatchMinimal)(nil), "CMsgDOTAMatchMinimal")
	proto.RegisterType((*CMsgDOTAMatchMinimal_Player)(nil), "CMsgDOTAMatchMinimal.Player")
	proto.RegisterType((*CMsgDOTAMatchMinimal_Tourney)(nil), "CMsgDOTAMatchMinimal.Tourney")
	proto.RegisterType((*CDOTAReplayDownloadInfo)(nil), "CDOTAReplayDownloadInfo")
	proto.RegisterType((*CDOTAReplayDownloadInfo_Highlight)(nil), "CDOTAReplayDownloadInfo.Highlight")
	proto.RegisterType((*CMsgWatchGame)(nil), "CMsgWatchGame")
	proto.RegisterType((*CMsgCancelWatchGame)(nil), "CMsgCancelWatchGame")
	proto.RegisterType((*CMsgWatchGameResponse)(nil), "CMsgWatchGameResponse")
	proto.RegisterType((*CMsgPartyLeaderWatchGamePrompt)(nil), "CMsgPartyLeaderWatchGamePrompt")
	proto.RegisterType((*CDOTABroadcasterInfo)(nil), "CDOTABroadcasterInfo")
	proto.RegisterEnum("CMsgWatchGameResponse_WatchGameResult", CMsgWatchGameResponse_WatchGameResult_name, CMsgWatchGameResponse_WatchGameResult_value)
}

func init() {
	proto.RegisterFile("dota_gcmessages_client_watch.proto", fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099)
}

var fileDescriptor_dota_gcmessages_client_watch_ef7345709b825099 = []byte{
	// 2255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x4b, 0x73, 0x23, 0xb7,
	0x11, 0xf6, 0xe8, 0x41, 0x72, 0x5a, 0xa2, 0x1e, 0xd0, 0xae, 0x34, 0xab, 0x87, 0x97, 0xa1, 0xd7,
	0x6b, 0xd6, 0xa6, 0xac, 0xb5, 0xb5, 0xa9, 0x38, 0xb5, 0x95, 0x54, 0x4c, 0x51, 0x5c, 0x99, 0x65,
	0x8a, 0x52, 0x0d, 0x29, 0xb9, 0xd6, 0x39, 0x4c, 0x41, 0x1c, 0x2c, 0x85, 0xd2, 0xcc, 0x80, 0x1e,
	0x80, 0x94, 0x95, 0x4b, 0x72, 0xcf, 0x25, 0xd7, 0xfc, 0x87, 0xfc, 0x87, 0x5c, 0x72, 0xc8, 0x35,
	0x39, 0xa6, 0x2a, 0xb7, 0x9c, 0xf3, 0x1b, 0x52, 0x68, 0xcc, 0x50, 0xc3, 0x87, 0x22, 0xc7, 0xae,
	0x54, 0x4e, 0x24, 0xbe, 0xfe, 0x1a, 0x0d, 0x34, 0xba, 0x1b, 0x8d, 0x81, 0xb2, 0x2f, 0x14, 0xf5,
	0x7a, 0xdd, 0x90, 0x49, 0x49, 0x7b, 0x4c, 0x7a, 0xdd, 0x80, 0xb3, 0x48, 0x79, 0x37, 0x54, 0x75,
	0xaf, 0xf6, 0xfb, 0xb1, 0x50, 0x62, 0x7b, 0x0b, 0x39, 0xf2, 0x8a, 0xc6, 0xcc, 0xf7, 0x58, 0x34,
	0x08, 0x65, 0x22, 0xd8, 0x9d, 0x52, 0x16, 0x61, 0x28, 0x22, 0x23, 0x2d, 0xff, 0xb3, 0x00, 0xa4,
	0xd6, 0x16, 0x83, 0xb8, 0xcb, 0x3a, 0x17, 0xc7, 0x34, 0x64, 0xed, 0x90, 0x06, 0x01, 0xf9, 0x00,
	0x8a, 0xb4, 0xab, 0xf8, 0x90, 0x2a, 0xe6, 0x29, 0x1e, 0x32, 0xc7, 0x2a, 0x59, 0x95, 0xa2, 0xbb,
	0x9c, 0x82, 0x1d, 0x1e, 0x32, 0xf2, 0x11, 0xac, 0xfa, 0x6c, 0x9c, 0x36, 0x87, 0xb4, 0x95, 0x3b,
	0x18, 0x89, 0xcf, 0x61, 0x55, 0xb2, 0x78, 0xc8, 0x62, 0x4f, 0x2a, 0x46, 0x43, 0x8f, 0xfb, 0xce,
	0x7c, 0xc9, 0xaa, 0x2c, 0xb8, 0x45, 0x03, 0xb7, 0x35, 0xda, 0xf0, 0xc9, 0x13, 0x28, 0x04, 0xe2,
	0xf2, 0xf2, 0x56, 0x13, 0x16, 0x90, 0x90, 0xc7, 0x71, 0xc3, 0x27, 0x3b, 0x60, 0x07, 0x8c, 0xf6,
	0x06, 0x4c, 0xcb, 0x16, 0xd1, 0x4a, 0xc1, 0x00, 0x0d, 0x9f, 0xec, 0x01, 0x18, 0x3d, 0x75, 0xdb,
	0x67, 0x4e, 0x0e, 0xa5, 0x36, 0x22, 0x9d, 0xdb, 0x3e, 0xd3, 0xba, 0x3d, 0x1a, 0x26, 0x2b, 0xcc,
	0x97, 0xac, 0xca, 0xa2, 0x5b, 0xd0, 0x00, 0xae, 0xed, 0x11, 0x2c, 0xfa, 0x2c, 0xa0, 0xb7, 0x4e,
	0x01, 0xd5, 0xcc, 0x80, 0xbc, 0x0f, 0x20, 0xfb, 0xac, 0xab, 0xa8, 0x12, 0xb1, 0x74, 0x6c, 0x14,
	0x65, 0x90, 0xd1, 0x94, 0xa1, 0xf0, 0x99, 0x03, 0x66, 0x39, 0x1a, 0x38, 0x11, 0x3e, 0x23, 0x4f,
	0x61, 0x89, 0x0e, 0x59, 0x4c, 0x7b, 0xcc, 0x0b, 0xc3, 0xd8, 0x59, 0x32, 0xda, 0x09, 0x74, 0x12,
	0xc6, 0xe4, 0x05, 0xac, 0xa3, 0x1f, 0x22, 0x3d, 0x45, 0x4c, 0x7d, 0x4e, 0x23, 0xe5, 0xac, 0x96,
	0xac, 0x8a, 0xed, 0xae, 0x6a, 0x41, 0x8b, 0x86, 0xcc, 0x35, 0x30, 0x79, 0x06, 0x2b, 0x77, 0x5c,
	0x9f, 0xc7, 0xcc, 0x59, 0x43, 0xe2, 0x72, 0x4a, 0x3c, 0xe2, 0x31, 0x1b, 0xcd, 0x18, 0x88, 0x9e,
	0x18, 0xcd, 0xe8, 0x94, 0xac, 0x4a, 0xce, 0xcc, 0xd8, 0x14, 0x3d, 0x31, 0x39, 0x23, 0x72, 0x71,
	0xc6, 0x27, 0x48, 0x5c, 0x4e, 0x89, 0x38, 0xe3, 0x1e, 0x80, 0x14, 0xb1, 0xf2, 0x64, 0x57, 0xc4,
	0xcc, 0x59, 0x37, 0x3e, 0xd5, 0x48, 0x5b, 0x03, 0xa4, 0x02, 0x6b, 0x01, 0x95, 0xca, 0x1b, 0xf4,
	0xfd, 0xd1, 0xe1, 0x93, 0x92, 0x55, 0x99, 0x73, 0x57, 0x34, 0x7e, 0x8e, 0x30, 0x3a, 0xf8, 0x47,
	0xb0, 0x9c, 0x2c, 0xc8, 0x0b, 0x18, 0xf5, 0x9d, 0x0d, 0x3c, 0x80, 0xa5, 0x04, 0x6b, 0x32, 0xea,
	0xeb, 0x68, 0x4b, 0x29, 0xc6, 0xdc, 0x23, 0x13, 0x6d, 0x09, 0x68, 0x2c, 0xee, 0x01, 0xe8, 0xc5,
	0x26, 0x8c, 0xc7, 0x66, 0x41, 0x1a, 0x31, 0xe2, 0x9f, 0x40, 0xbe, 0x1f, 0xd0, 0x5b, 0x16, 0x4b,
	0x67, 0xb3, 0x34, 0x5f, 0x59, 0x3a, 0xd8, 0xde, 0x9f, 0x8e, 0xeb, 0xfd, 0x33, 0xa4, 0xb8, 0x29,
	0x95, 0x7c, 0x08, 0x2b, 0x97, 0x03, 0x1e, 0xf8, 0x3c, 0xea, 0x79, 0x52, 0x51, 0xc5, 0x9c, 0xad,
	0x92, 0x55, 0xc9, 0xbb, 0xc5, 0x14, 0x6d, 0x6b, 0x90, 0x54, 0x61, 0xef, 0x86, 0xb1, 0x6b, 0x16,
	0xf9, 0x9e, 0x12, 0x83, 0x38, 0x62, 0xb7, 0xe6, 0x97, 0x86, 0x3a, 0x0d, 0xb9, 0xef, 0x6c, 0xe3,
	0x72, 0xb6, 0x13, 0x52, 0xc7, 0x70, 0x3a, 0x23, 0x4a, 0xc3, 0x27, 0x3f, 0x03, 0x67, 0x72, 0x0a,
	0x9f, 0x0f, 0xb9, 0xe4, 0x22, 0x72, 0x76, 0x50, 0x7b, 0x73, 0x5c, 0xfb, 0x28, 0x91, 0x92, 0x5f,
	0xc0, 0xce, 0xa4, 0xa6, 0xbc, 0xe6, 0x41, 0xe0, 0x05, 0x6c, 0xc8, 0x02, 0x67, 0x17, 0x95, 0x9d,
	0x71, 0xe5, 0xb6, 0x26, 0x34, 0xb5, 0x7c, 0xd6, 0xda, 0x2f, 0x63, 0xda, 0xbd, 0x66, 0xca, 0x8b,
	0xc5, 0x20, 0xf2, 0x9d, 0xbd, 0x59, 0x6b, 0x3f, 0x34, 0x14, 0x57, 0x33, 0xb6, 0x3f, 0x87, 0x9c,
	0x71, 0x9c, 0x3e, 0x04, 0xda, 0xed, 0x8a, 0x81, 0xd9, 0xb5, 0x29, 0x0a, 0x76, 0x82, 0x34, 0x7c,
	0xb2, 0x05, 0xf9, 0x2b, 0x16, 0x0b, 0x2d, 0x33, 0x95, 0x20, 0xa7, 0x87, 0x0d, 0xbf, 0xfc, 0x0f,
	0x0b, 0xca, 0xb5, 0x13, 0xd9, 0xab, 0x61, 0xe1, 0xea, 0x88, 0xe3, 0xda, 0x1b, 0xae, 0x6d, 0xf5,
	0xb3, 0x47, 0x24, 0x31, 0xe8, 0x18, 0x8d, 0xbb, 0x57, 0xde, 0x35, 0xbb, 0xc5, 0xe9, 0x6d, 0xd7,
	0x36, 0xc8, 0x97, 0xec, 0x76, 0xbc, 0x08, 0xcc, 0x4d, 0x14, 0x81, 0x8c, 0xed, 0xf9, 0xac, 0x6d,
	0x9c, 0x54, 0xd1, 0x58, 0x79, 0x3a, 0x41, 0xb1, 0xae, 0xe8, 0x48, 0xd6, 0x88, 0x36, 0xaa, 0x8b,
	0x13, 0xa6, 0x72, 0xc0, 0xa5, 0xf2, 0x78, 0xe4, 0xb3, 0x6f, 0x93, 0xfa, 0x52, 0xd4, 0x70, 0x93,
	0x4b, 0xd5, 0xd0, 0x20, 0x1a, 0x4f, 0x8a, 0x93, 0x74, 0x72, 0xa5, 0xf9, 0xca, 0x82, 0x5b, 0x48,
	0xaa, 0x93, 0x2c, 0xff, 0x6b, 0x0e, 0x5e, 0xe8, 0xfd, 0x1d, 0xd7, 0x3a, 0xc2, 0xec, 0x71, 0xd6,
	0xfe, 0x5c, 0x26, 0xfb, 0x22, 0x92, 0xec, 0xff, 0xb2, 0xcf, 0x1d, 0xb0, 0xa3, 0x41, 0x88, 0x42,
	0x99, 0x56, 0xd0, 0x68, 0x10, 0x1a, 0xc7, 0xcf, 0x70, 0x42, 0x6e, 0x96, 0x13, 0x3e, 0x49, 0xea,
	0x9e, 0xe6, 0x39, 0x79, 0xcc, 0xb3, 0x8d, 0x19, 0x79, 0x66, 0x8a, 0xa1, 0x56, 0xd3, 0x19, 0xa6,
	0xeb, 0x26, 0x7f, 0xc7, 0xbb, 0x89, 0x6d, 0x5d, 0x68, 0x0b, 0x6e, 0x31, 0x45, 0xcd, 0x02, 0xf6,
	0xa1, 0x70, 0x29, 0x92, 0xa5, 0xeb, 0x72, 0x7b, 0xcf, 0xbc, 0xf9, 0x4b, 0x81, 0xbb, 0x29, 0x7f,
	0x0d, 0xcf, 0xc6, 0xfd, 0xdd, 0x11, 0xfd, 0xaf, 0xc6, 0x22, 0xd8, 0xcc, 0x7b, 0x00, 0x10, 0xf0,
	0x21, 0x4b, 0x4c, 0x5b, 0xf7, 0xaf, 0xd8, 0xd6, 0x34, 0xd4, 0x29, 0xff, 0x06, 0x9e, 0x8e, 0xc7,
	0x6a, 0x47, 0xf4, 0x4f, 0xf4, 0x55, 0xab, 0x4f, 0xf0, 0x9b, 0x01, 0x93, 0x2a, 0x7b, 0x08, 0xd6,
	0xd8, 0x21, 0xbc, 0x80, 0x75, 0x53, 0x5b, 0xbc, 0x4c, 0x9e, 0x98, 0x23, 0x5c, 0x35, 0x82, 0x6a,
	0x36, 0x5b, 0xb2, 0xd7, 0x61, 0xd1, 0xcd, 0x99, 0x7b, 0xb0, 0xfc, 0x11, 0x7c, 0x38, 0xb5, 0x80,
	0x26, 0x9e, 0xff, 0xf8, 0x32, 0x66, 0x12, 0xdf, 0xc4, 0x9c, 0x45, 0xfe, 0x04, 0xf1, 0x10, 0x3e,
	0x18, 0x27, 0x26, 0xf2, 0x13, 0x1e, 0xf1, 0x90, 0x06, 0xe9, 0xb6, 0x76, 0xc0, 0x0e, 0xb5, 0x00,
	0x63, 0xdc, 0x32, 0x31, 0x8e, 0x80, 0x8e, 0xf1, 0xa1, 0x71, 0xf9, 0xfd, 0x73, 0x24, 0xc1, 0xfd,
	0x12, 0xf2, 0xa1, 0x91, 0x24, 0xfe, 0x7e, 0xbc, 0xaf, 0xf5, 0x8e, 0x4e, 0x3b, 0x55, 0xd4, 0x48,
	0xf9, 0x29, 0x0b, 0xaf, 0x6f, 0x7d, 0x97, 0xe0, 0x18, 0x9d, 0x55, 0x70, 0x6d, 0x8d, 0x20, 0xbd,
	0xfc, 0x16, 0x9e, 0x4f, 0x1d, 0xf5, 0x84, 0x37, 0xa6, 0x2d, 0xcf, 0x7d, 0x17, 0xcb, 0x33, 0xa7,
	0x9e, 0xf0, 0xdf, 0xf7, 0xdc, 0x54, 0xf9, 0x6f, 0x16, 0xec, 0xce, 0xac, 0x78, 0x27, 0x77, 0xbb,
	0xce, 0xa4, 0xab, 0x35, 0x23, 0x5d, 0xbf, 0x47, 0x0d, 0xd8, 0x01, 0xfb, 0x1d, 0xae, 0x3f, 0x6d,
	0xa1, 0x8a, 0x6e, 0xc1, 0x00, 0x0d, 0x5f, 0xf7, 0x25, 0x89, 0x10, 0xd3, 0x77, 0x11, 0x1d, 0x0d,
	0x06, 0xc2, 0x5c, 0x7d, 0x0a, 0x4b, 0x89, 0x4d, 0x24, 0xe4, 0x0c, 0xc1, 0x40, 0x9a, 0x50, 0xfe,
	0x8b, 0x75, 0x4f, 0x99, 0x9b, 0x7d, 0x1e, 0xff, 0xab, 0x2d, 0xde, 0xc5, 0xe8, 0x42, 0x69, 0x5e,
	0x6b, 0xa5, 0x31, 0x4a, 0x2a, 0x77, 0xc7, 0xb4, 0x88, 0xc7, 0xb4, 0x32, 0x7e, 0x4c, 0x77, 0xe7,
	0xf3, 0x0a, 0x36, 0xb5, 0xa4, 0x6d, 0x7a, 0x3a, 0x66, 0x4e, 0x1d, 0x97, 0xf5, 0x04, 0x0a, 0xa3,
	0x36, 0xd5, 0xc2, 0xce, 0x28, 0x2f, 0x93, 0xc4, 0x3c, 0x86, 0xf7, 0x67, 0x2b, 0x8d, 0xb6, 0xac,
	0xcb, 0x5d, 0xa6, 0xd5, 0x4d, 0x4e, 0x21, 0x37, 0xd6, 0xe9, 0x72, 0xbf, 0xfc, 0x3b, 0x1b, 0x1e,
	0xcd, 0x8a, 0x1f, 0x6d, 0x3c, 0xdd, 0x1d, 0x1a, 0x5f, 0x48, 0x56, 0x9c, 0xad, 0xef, 0xa3, 0x4e,
	0x3b, 0x9f, 0x78, 0x13, 0xfb, 0xac, 0x6d, 0x28, 0xf8, 0x83, 0x98, 0x2a, 0xdd, 0x50, 0x18, 0x8f,
	0x8d, 0xc6, 0xe4, 0x97, 0xd9, 0x76, 0x55, 0x2f, 0x68, 0xe5, 0x60, 0x65, 0x5f, 0xdb, 0xf6, 0x8e,
	0x93, 0xa6, 0xf5, 0x35, 0x31, 0xc3, 0xea, 0x49, 0xfd, 0xe4, 0xf4, 0xa8, 0xee, 0xb5, 0x4e, 0x5b,
	0xf5, 0x4c, 0x4b, 0xfb, 0xd3, 0xbb, 0xee, 0x2a, 0x87, 0x7e, 0xdd, 0x9d, 0x19, 0xfe, 0x53, 0xfd,
	0xd5, 0x67, 0x90, 0x4f, 0x9a, 0x0e, 0x6c, 0xbc, 0x97, 0x0e, 0xf6, 0x66, 0xeb, 0x25, 0x35, 0xdb,
	0x4d, 0xd9, 0xa4, 0x09, 0x45, 0xe3, 0x07, 0x31, 0x50, 0x5d, 0x11, 0x32, 0xbc, 0x35, 0xf4, 0xaa,
	0xeb, 0xa8, 0x77, 0x6a, 0xd0, 0xd7, 0x5b, 0xd7, 0xde, 0x18, 0xe0, 0x9d, 0x47, 0xd7, 0x91, 0xb8,
	0x89, 0xdc, 0xe5, 0x30, 0x83, 0x6e, 0xff, 0xc9, 0xfa, 0xa1, 0x1d, 0x8c, 0x7e, 0x27, 0xe8, 0x9e,
	0x4a, 0x26, 0xbe, 0x35, 0x03, 0xb2, 0x09, 0x39, 0x9f, 0x51, 0x75, 0x25, 0x93, 0x64, 0x4b, 0x46,
	0xc4, 0x81, 0x3c, 0x95, 0x92, 0x4b, 0x95, 0x5e, 0xb5, 0xe9, 0x50, 0xcf, 0xc3, 0x15, 0x0b, 0x8d,
	0x1f, 0x8b, 0xae, 0x19, 0xe8, 0xcc, 0x4b, 0xae, 0x0d, 0x19, 0x08, 0x85, 0xbe, 0x2a, 0xba, 0x60,
	0xa0, 0x76, 0x20, 0xd4, 0xf6, 0xdf, 0x17, 0x20, 0x9f, 0x38, 0x69, 0x3c, 0x6f, 0xac, 0x89, 0xbc,
	0x79, 0x0a, 0x4b, 0x92, 0xc5, 0x9c, 0x49, 0xf3, 0x18, 0x2a, 0x24, 0x4f, 0x17, 0x84, 0xf0, 0x35,
	0x74, 0x47, 0x18, 0x5d, 0xb6, 0x23, 0x02, 0xc6, 0xff, 0x83, 0xcd, 0x2e, 0x3c, 0xd8, 0xec, 0xbe,
	0x81, 0xd2, 0x54, 0xcb, 0xca, 0xa8, 0x14, 0x91, 0xa7, 0x62, 0xd1, 0xbf, 0xc2, 0x07, 0x9e, 0x79,
	0x16, 0xed, 0x4e, 0xf4, 0xad, 0xc8, 0xea, 0x20, 0xe9, 0x81, 0xa6, 0x79, 0xf9, 0x87, 0x34, 0xcd,
	0xc5, 0x07, 0x9a, 0xe6, 0xe7, 0xb0, 0x9a, 0xbe, 0x48, 0xd2, 0x52, 0x60, 0xc2, 0x21, 0x7d, 0xa8,
	0x74, 0xcc, 0x8b, 0xf5, 0x05, 0xac, 0x8f, 0xf1, 0xb4, 0x07, 0x30, 0x42, 0x6c, 0x77, 0x35, 0xc3,
	0xd4, 0xef, 0xb4, 0x29, 0xae, 0x7e, 0x7f, 0x25, 0xd5, 0x21, 0xcb, 0xd5, 0x2f, 0x30, 0x52, 0x82,
	0x65, 0x7c, 0xec, 0xa4, 0xc6, 0x4d, 0x10, 0xe1, 0x03, 0x28, 0xb1, 0xfc, 0x0c, 0x56, 0xee, 0x18,
	0x68, 0x36, 0x67, 0xde, 0x85, 0x29, 0x07, 0x6d, 0x8e, 0xb1, 0xd0, 0x60, 0xde, 0xbc, 0xf5, 0x52,
	0x96, 0xb6, 0x56, 0xfe, 0xc3, 0x1c, 0x6c, 0xd5, 0x74, 0x4e, 0xba, 0x4c, 0x87, 0xdc, 0x91, 0xb8,
	0x89, 0x02, 0x41, 0xfd, 0x46, 0xf4, 0x4e, 0x90, 0x1f, 0xc3, 0xa2, 0xb9, 0x97, 0x2d, 0xcc, 0xdf,
	0x7b, 0xae, 0x3d, 0xc3, 0xd1, 0xc1, 0xad, 0xb8, 0x0a, 0x4c, 0x75, 0xb2, 0x5d, 0x33, 0x20, 0x25,
	0x58, 0xf2, 0x99, 0xec, 0xc6, 0xbc, 0x3f, 0x2a, 0x4e, 0xb6, 0x9b, 0x85, 0x08, 0x81, 0x05, 0xc9,
	0x7f, 0x9d, 0x36, 0xad, 0xf8, 0x5f, 0x63, 0x8a, 0xf6, 0x4c, 0x1d, 0xb7, 0x5d, 0xfc, 0xaf, 0xb7,
	0xc3, 0xbe, 0xd5, 0x69, 0xe4, 0x89, 0xc8, 0xf3, 0xb9, 0xbc, 0x4e, 0xee, 0xa8, 0x65, 0x83, 0x9e,
	0x46, 0x47, 0x5c, 0x5e, 0x6f, 0x7f, 0x09, 0xf6, 0x17, 0xbc, 0x77, 0x15, 0xf0, 0xde, 0x95, 0x22,
	0xbb, 0x60, 0xeb, 0x7a, 0x29, 0x15, 0x0d, 0xfb, 0x69, 0xba, 0x8f, 0x80, 0xc9, 0xa5, 0xcd, 0x4d,
	0x2d, 0xad, 0xfc, 0x67, 0x0b, 0x8a, 0x7a, 0xcb, 0x5f, 0xe9, 0x0d, 0x62, 0x7e, 0x4c, 0x97, 0x78,
	0x6b, 0x46, 0x89, 0xd7, 0xb4, 0xe4, 0x33, 0xcd, 0x90, 0xc5, 0x32, 0x9d, 0xbd, 0xe8, 0x16, 0x0d,
	0x7a, 0x61, 0x40, 0xf2, 0x09, 0x3c, 0xc2, 0xcf, 0x38, 0xde, 0xc4, 0x9c, 0xf3, 0x38, 0x27, 0x41,
	0x59, 0x7b, 0x6c, 0xe2, 0xff, 0xf0, 0x95, 0xc4, 0x81, 0x7c, 0xcc, 0x7a, 0x5c, 0x44, 0xc6, 0x6d,
	0x45, 0x37, 0x1d, 0x96, 0x1f, 0xc3, 0x06, 0x76, 0x23, 0x34, 0xea, 0xb2, 0x60, 0xb4, 0x97, 0xf2,
	0x5f, 0x17, 0xe0, 0xf1, 0xd8, 0xee, 0x46, 0x17, 0xd9, 0xaf, 0x60, 0xdd, 0xac, 0x0b, 0x2f, 0x8e,
	0x98, 0xc9, 0x41, 0xa0, 0x70, 0xa3, 0x2b, 0x07, 0xcf, 0xf7, 0x67, 0xaa, 0xec, 0x67, 0x91, 0x41,
	0xa0, 0x5e, 0xe7, 0xcf, 0xea, 0xad, 0xa3, 0x46, 0xeb, 0xd8, 0x5d, 0xbd, 0x19, 0x97, 0x90, 0x4f,
	0xe1, 0xb1, 0xc4, 0x0e, 0xdc, 0x53, 0x43, 0xaf, 0x3f, 0xb8, 0x0c, 0x78, 0xd7, 0xa3, 0xbe, 0x1f,
	0x27, 0x2e, 0x22, 0x46, 0xd8, 0x19, 0x9e, 0xa1, 0xa8, 0xea, 0xfb, 0x31, 0x79, 0x05, 0x9b, 0x19,
	0x95, 0xd8, 0x7c, 0x73, 0x42, 0x1d, 0x53, 0x90, 0x37, 0x46, 0x3a, 0x46, 0x86, 0x4a, 0xcf, 0x60,
	0x25, 0xa3, 0x24, 0x62, 0x95, 0x44, 0xd8, 0xf2, 0x88, 0x2c, 0x62, 0x45, 0xf6, 0x61, 0x03, 0x37,
	0x39, 0x71, 0x02, 0x8b, 0x78, 0x02, 0xeb, 0x5a, 0x34, 0x7e, 0x00, 0xf7, 0x1d, 0x59, 0xee, 0xde,
	0x23, 0xfb, 0x39, 0xec, 0x18, 0x0d, 0x35, 0xf4, 0x06, 0x11, 0xff, 0x66, 0xa0, 0x8d, 0x75, 0x63,
	0xa6, 0xbc, 0xae, 0xbe, 0x91, 0x4d, 0x4e, 0x6e, 0x21, 0xa5, 0x33, 0x3c, 0x47, 0x42, 0x1b, 0xe5,
	0x35, 0xe1, 0xb3, 0xf2, 0x1f, 0x2d, 0x58, 0x9d, 0xf0, 0x2d, 0x59, 0x82, 0xd4, 0xbb, 0x6b, 0xef,
	0x11, 0x1b, 0x16, 0xdd, 0x7a, 0xf5, 0xe8, 0xed, 0x9a, 0x45, 0x36, 0x81, 0xe8, 0x3b, 0xbc, 0x5d,
	0x77, 0x2f, 0xea, 0x6e, 0xeb, 0xb4, 0xf3, 0xe6, 0xf4, 0xbc, 0x75, 0xb4, 0x36, 0x47, 0x56, 0x61,
	0xe9, 0xbc, 0x55, 0xbd, 0xa8, 0x36, 0x9a, 0xd5, 0xc3, 0x66, 0x7d, 0x6d, 0x9e, 0x14, 0xc1, 0xae,
	0x55, 0x5b, 0xb5, 0x7a, 0xb3, 0x59, 0x3f, 0x5a, 0x5b, 0x20, 0x5b, 0xb0, 0xd1, 0x68, 0xd5, 0x4e,
	0x4f, 0xce, 0xaa, 0x9d, 0xc6, 0x61, 0xb3, 0x7e, 0x51, 0x77, 0xdb, 0x8d, 0xd3, 0xd6, 0xda, 0x22,
	0xd9, 0x83, 0x27, 0x27, 0x8d, 0x76, 0xbb, 0xd1, 0x3a, 0x6e, 0xd6, 0xab, 0xc7, 0xe7, 0xf5, 0xf6,
	0xf9, 0x61, 0xbb, 0xe6, 0x36, 0xce, 0x3a, 0x5a, 0x9c, 0x23, 0xeb, 0x50, 0x6c, 0x9e, 0x1e, 0x1e,
	0xbe, 0x1d, 0x99, 0xca, 0x97, 0xcf, 0x4c, 0x93, 0x74, 0x46, 0x63, 0x75, 0xdb, 0x64, 0xd4, 0x67,
	0xf1, 0x68, 0xf1, 0x67, 0xb1, 0x08, 0xfb, 0xff, 0xb5, 0xc3, 0xcb, 0xbf, 0x9f, 0x87, 0x47, 0x58,
	0x9f, 0x0e, 0x63, 0x41, 0xfd, 0x2e, 0x95, 0x8a, 0xc5, 0x58, 0x9c, 0x1e, 0xb8, 0xcc, 0x67, 0x7c,
	0x77, 0x9c, 0x9b, 0x4a, 0xd5, 0x86, 0xaf, 0x4b, 0x8d, 0x7e, 0xfd, 0x61, 0x24, 0x15, 0x5c, 0xfc,
	0x3f, 0xfb, 0x1b, 0xdd, 0xc2, 0x77, 0xfd, 0x46, 0xb7, 0x38, 0xe3, 0x1b, 0x9d, 0xe9, 0xdf, 0x7a,
	0x2c, 0x5b, 0xad, 0x6d, 0x44, 0xb0, 0x54, 0x4f, 0xdc, 0xcb, 0xf9, 0xa9, 0x7b, 0xf9, 0xc1, 0x9b,
	0xfd, 0x73, 0xd8, 0x1d, 0xf4, 0xbb, 0x22, 0xe4, 0x51, 0xcf, 0xbb, 0x4c, 0x3d, 0xe5, 0xdd, 0x55,
	0x3f, 0x73, 0xd5, 0x6f, 0xa7, 0x9c, 0x91, 0x33, 0x3b, 0xa3, 0x72, 0x58, 0x81, 0x35, 0x1a, 0x04,
	0xe2, 0xc6, 0xc3, 0x37, 0xf3, 0x90, 0xfb, 0x4c, 0xe0, 0x6d, 0x5f, 0x70, 0x57, 0x10, 0x6f, 0xf2,
	0x21, 0xbb, 0xd0, 0xe8, 0xe1, 0x67, 0x5f, 0x58, 0x5f, 0x7f, 0xd2, 0xe3, 0xea, 0x6a, 0x70, 0xb9,
	0xdf, 0x15, 0xe1, 0xcb, 0x4f, 0x5f, 0x5d, 0xbf, 0xec, 0x89, 0x8f, 0xd1, 0xcf, 0x1f, 0xc7, 0xcc,
	0xe4, 0x97, 0x7c, 0x89, 0x1f, 0x99, 0x2f, 0x07, 0xef, 0x5e, 0xfa, 0x42, 0xd1, 0x83, 0xdf, 0x5a,
	0xef, 0xfd, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x48, 0xf1, 0xf7, 0x45, 0xcc, 0x16, 0x00, 0x00,
}
