// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_partnerapps.steamclient.proto

package unified

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CPartnerApps_RequestUploadToken_Request struct {
	Filename         *string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Appid            *uint32 `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_RequestUploadToken_Request) Reset() {
	*m = CPartnerApps_RequestUploadToken_Request{}
}
func (m *CPartnerApps_RequestUploadToken_Request) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_RequestUploadToken_Request) ProtoMessage()    {}
func (*CPartnerApps_RequestUploadToken_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{0}
}

func (m *CPartnerApps_RequestUploadToken_Request) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *CPartnerApps_RequestUploadToken_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

type CPartnerApps_RequestUploadToken_Response struct {
	UploadToken      *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"upload_token,omitempty"`
	Location         *string `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	RoutingId        *uint64 `protobuf:"varint,3,opt,name=routing_id,json=routingId" json:"routing_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_RequestUploadToken_Response) Reset() {
	*m = CPartnerApps_RequestUploadToken_Response{}
}
func (m *CPartnerApps_RequestUploadToken_Response) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_RequestUploadToken_Response) ProtoMessage()    {}
func (*CPartnerApps_RequestUploadToken_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{1}
}

func (m *CPartnerApps_RequestUploadToken_Response) GetUploadToken() uint64 {
	if m != nil && m.UploadToken != nil {
		return *m.UploadToken
	}
	return 0
}

func (m *CPartnerApps_RequestUploadToken_Response) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *CPartnerApps_RequestUploadToken_Response) GetRoutingId() uint64 {
	if m != nil && m.RoutingId != nil {
		return *m.RoutingId
	}
	return 0
}

type CPartnerApps_FinishUpload_Request struct {
	UploadToken      *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"upload_token,omitempty"`
	RoutingId        *uint64 `protobuf:"varint,2,opt,name=routing_id,json=routingId" json:"routing_id,omitempty"`
	AppId            *uint32 `protobuf:"varint,3,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_FinishUpload_Request) Reset()         { *m = CPartnerApps_FinishUpload_Request{} }
func (m *CPartnerApps_FinishUpload_Request) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FinishUpload_Request) ProtoMessage()    {}
func (*CPartnerApps_FinishUpload_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{2}
}

func (m *CPartnerApps_FinishUpload_Request) GetUploadToken() uint64 {
	if m != nil && m.UploadToken != nil {
		return *m.UploadToken
	}
	return 0
}

func (m *CPartnerApps_FinishUpload_Request) GetRoutingId() uint64 {
	if m != nil && m.RoutingId != nil {
		return *m.RoutingId
	}
	return 0
}

func (m *CPartnerApps_FinishUpload_Request) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

type CPartnerApps_FinishUploadKVSign_Response struct {
	SignedInstallscript *string `protobuf:"bytes,1,opt,name=signed_installscript,json=signedInstallscript" json:"signed_installscript,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *CPartnerApps_FinishUploadKVSign_Response) Reset() {
	*m = CPartnerApps_FinishUploadKVSign_Response{}
}
func (m *CPartnerApps_FinishUploadKVSign_Response) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FinishUploadKVSign_Response) ProtoMessage()    {}
func (*CPartnerApps_FinishUploadKVSign_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{3}
}

func (m *CPartnerApps_FinishUploadKVSign_Response) GetSignedInstallscript() string {
	if m != nil && m.SignedInstallscript != nil {
		return *m.SignedInstallscript
	}
	return ""
}

type CPartnerApps_FinishUploadLegacyDRM_Request struct {
	UploadToken      *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"upload_token,omitempty"`
	RoutingId        *uint64 `protobuf:"varint,2,opt,name=routing_id,json=routingId" json:"routing_id,omitempty"`
	AppId            *uint32 `protobuf:"varint,3,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	Flags            *uint32 `protobuf:"varint,4,opt,name=flags" json:"flags,omitempty"`
	ToolName         *string `protobuf:"bytes,5,opt,name=tool_name,json=toolName" json:"tool_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) Reset() {
	*m = CPartnerApps_FinishUploadLegacyDRM_Request{}
}
func (m *CPartnerApps_FinishUploadLegacyDRM_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CPartnerApps_FinishUploadLegacyDRM_Request) ProtoMessage() {}
func (*CPartnerApps_FinishUploadLegacyDRM_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{4}
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetUploadToken() uint64 {
	if m != nil && m.UploadToken != nil {
		return *m.UploadToken
	}
	return 0
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetRoutingId() uint64 {
	if m != nil && m.RoutingId != nil {
		return *m.RoutingId
	}
	return 0
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetToolName() string {
	if m != nil && m.ToolName != nil {
		return *m.ToolName
	}
	return ""
}

type CPartnerApps_FinishUploadLegacyDRM_Response struct {
	FileId           *string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) Reset() {
	*m = CPartnerApps_FinishUploadLegacyDRM_Response{}
}
func (m *CPartnerApps_FinishUploadLegacyDRM_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CPartnerApps_FinishUploadLegacyDRM_Response) ProtoMessage() {}
func (*CPartnerApps_FinishUploadLegacyDRM_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{5}
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) GetFileId() string {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return ""
}

type CPartnerApps_FinishUpload_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CPartnerApps_FinishUpload_Response) Reset()         { *m = CPartnerApps_FinishUpload_Response{} }
func (m *CPartnerApps_FinishUpload_Response) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FinishUpload_Response) ProtoMessage()    {}
func (*CPartnerApps_FinishUpload_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{6}
}

type CPartnerApps_FindDRMUploads_Request struct {
	AppId            *int32 `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CPartnerApps_FindDRMUploads_Request) Reset()         { *m = CPartnerApps_FindDRMUploads_Request{} }
func (m *CPartnerApps_FindDRMUploads_Request) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FindDRMUploads_Request) ProtoMessage()    {}
func (*CPartnerApps_FindDRMUploads_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{7}
}

func (m *CPartnerApps_FindDRMUploads_Request) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

type CPartnerApps_ExistingDRMUpload struct {
	FileId           *string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	AppId            *uint32 `protobuf:"varint,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	ActorId          *int32  `protobuf:"varint,3,opt,name=actor_id,json=actorId" json:"actor_id,omitempty"`
	SuppliedName     *string `protobuf:"bytes,5,opt,name=supplied_name,json=suppliedName" json:"supplied_name,omitempty"`
	Flags            *uint32 `protobuf:"varint,6,opt,name=flags" json:"flags,omitempty"`
	ModType          *string `protobuf:"bytes,7,opt,name=mod_type,json=modType" json:"mod_type,omitempty"`
	Timestamp        *uint32 `protobuf:"fixed32,8,opt,name=timestamp" json:"timestamp,omitempty"`
	OrigFileId       *string `protobuf:"bytes,9,opt,name=orig_file_id,json=origFileId" json:"orig_file_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_ExistingDRMUpload) Reset()                    { *m = CPartnerApps_ExistingDRMUpload{} }
func (m *CPartnerApps_ExistingDRMUpload) String() string            { return proto.CompactTextString(m) }
func (*CPartnerApps_ExistingDRMUpload) ProtoMessage()               {}
func (*CPartnerApps_ExistingDRMUpload) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{8} }

func (m *CPartnerApps_ExistingDRMUpload) GetFileId() string {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return ""
}

func (m *CPartnerApps_ExistingDRMUpload) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *CPartnerApps_ExistingDRMUpload) GetActorId() int32 {
	if m != nil && m.ActorId != nil {
		return *m.ActorId
	}
	return 0
}

func (m *CPartnerApps_ExistingDRMUpload) GetSuppliedName() string {
	if m != nil && m.SuppliedName != nil {
		return *m.SuppliedName
	}
	return ""
}

func (m *CPartnerApps_ExistingDRMUpload) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *CPartnerApps_ExistingDRMUpload) GetModType() string {
	if m != nil && m.ModType != nil {
		return *m.ModType
	}
	return ""
}

func (m *CPartnerApps_ExistingDRMUpload) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *CPartnerApps_ExistingDRMUpload) GetOrigFileId() string {
	if m != nil && m.OrigFileId != nil {
		return *m.OrigFileId
	}
	return ""
}

type CPartnerApps_FindDRMUploads_Response struct {
	Uploads          []*CPartnerApps_ExistingDRMUpload `protobuf:"bytes,1,rep,name=uploads" json:"uploads,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *CPartnerApps_FindDRMUploads_Response) Reset()         { *m = CPartnerApps_FindDRMUploads_Response{} }
func (m *CPartnerApps_FindDRMUploads_Response) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FindDRMUploads_Response) ProtoMessage()    {}
func (*CPartnerApps_FindDRMUploads_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{9}
}

func (m *CPartnerApps_FindDRMUploads_Response) GetUploads() []*CPartnerApps_ExistingDRMUpload {
	if m != nil {
		return m.Uploads
	}
	return nil
}

type CPartnerApps_Download_Request struct {
	FileId           *string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	AppId            *int32  `protobuf:"varint,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_Download_Request) Reset()                    { *m = CPartnerApps_Download_Request{} }
func (m *CPartnerApps_Download_Request) String() string            { return proto.CompactTextString(m) }
func (*CPartnerApps_Download_Request) ProtoMessage()               {}
func (*CPartnerApps_Download_Request) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{10} }

func (m *CPartnerApps_Download_Request) GetFileId() string {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return ""
}

func (m *CPartnerApps_Download_Request) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

type CPartnerApps_Download_Response struct {
	DownloadUrl      *string `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl" json:"download_url,omitempty"`
	AppId            *int32  `protobuf:"varint,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_Download_Response) Reset()         { *m = CPartnerApps_Download_Response{} }
func (m *CPartnerApps_Download_Response) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_Download_Response) ProtoMessage()    {}
func (*CPartnerApps_Download_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{11}
}

func (m *CPartnerApps_Download_Response) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *CPartnerApps_Download_Response) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func init() {
	proto.RegisterType((*CPartnerApps_RequestUploadToken_Request)(nil), "CPartnerApps_RequestUploadToken_Request")
	proto.RegisterType((*CPartnerApps_RequestUploadToken_Response)(nil), "CPartnerApps_RequestUploadToken_Response")
	proto.RegisterType((*CPartnerApps_FinishUpload_Request)(nil), "CPartnerApps_FinishUpload_Request")
	proto.RegisterType((*CPartnerApps_FinishUploadKVSign_Response)(nil), "CPartnerApps_FinishUploadKVSign_Response")
	proto.RegisterType((*CPartnerApps_FinishUploadLegacyDRM_Request)(nil), "CPartnerApps_FinishUploadLegacyDRM_Request")
	proto.RegisterType((*CPartnerApps_FinishUploadLegacyDRM_Response)(nil), "CPartnerApps_FinishUploadLegacyDRM_Response")
	proto.RegisterType((*CPartnerApps_FinishUpload_Response)(nil), "CPartnerApps_FinishUpload_Response")
	proto.RegisterType((*CPartnerApps_FindDRMUploads_Request)(nil), "CPartnerApps_FindDRMUploads_Request")
	proto.RegisterType((*CPartnerApps_ExistingDRMUpload)(nil), "CPartnerApps_ExistingDRMUpload")
	proto.RegisterType((*CPartnerApps_FindDRMUploads_Response)(nil), "CPartnerApps_FindDRMUploads_Response")
	proto.RegisterType((*CPartnerApps_Download_Request)(nil), "CPartnerApps_Download_Request")
	proto.RegisterType((*CPartnerApps_Download_Response)(nil), "CPartnerApps_Download_Response")
}

func init() { proto.RegisterFile("steammessages_partnerapps.steamclient.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 920 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xd6, 0xa6, 0x4d, 0x6c, 0xbf, 0xa4, 0x1c, 0x86, 0x46, 0x6c, 0x0d, 0x6d, 0xa7, 0x9b, 0x20,
	0x4c, 0x13, 0x6d, 0x20, 0x1c, 0x10, 0x52, 0x0f, 0x40, 0x52, 0x57, 0x56, 0x69, 0x40, 0xdb, 0x96,
	0x03, 0x08, 0xad, 0xc6, 0xbb, 0xe3, 0xed, 0x88, 0xdd, 0x9d, 0x61, 0x66, 0x16, 0x6a, 0x89, 0x0b,
	0x3e, 0x71, 0xe1, 0x0f, 0xe0, 0xce, 0x0d, 0x84, 0xc4, 0xc1, 0x12, 0x7f, 0x1e, 0x9a, 0xfd, 0x61,
	0xef, 0x3a, 0xd8, 0x5d, 0x0e, 0x11, 0xc7, 0xf7, 0xe6, 0xcd, 0x7b, 0xdf, 0x7c, 0xef, 0xcd, 0x37,
	0x03, 0x47, 0x4a, 0x53, 0x92, 0x24, 0x54, 0x29, 0x12, 0x51, 0xe5, 0x0b, 0x22, 0x75, 0x4a, 0x25,
	0x11, 0x42, 0xb9, 0xf9, 0x4a, 0x10, 0x33, 0x9a, 0x6a, 0x57, 0x48, 0xae, 0x79, 0x1f, 0x47, 0x9c,
	0x47, 0x31, 0x3d, 0xc9, 0xad, 0x71, 0x36, 0x39, 0x09, 0xa9, 0x0a, 0x24, 0x13, 0x9a, 0xcb, 0x32,
	0xe2, 0xb8, 0x99, 0x2e, 0x4b, 0xd9, 0x84, 0xd1, 0xd0, 0x1f, 0x13, 0x45, 0x2f, 0xe7, 0x73, 0xbe,
	0x86, 0x77, 0xce, 0xbe, 0x28, 0x2a, 0x7e, 0x22, 0x84, 0xf2, 0x3d, 0xfa, 0x5d, 0x46, 0x95, 0x7e,
	0x2e, 0x62, 0x4e, 0xc2, 0x67, 0xfc, 0x5b, 0x9a, 0x56, 0x2e, 0xd4, 0x87, 0xee, 0x84, 0xc5, 0x34,
	0x25, 0x09, 0xb5, 0x2d, 0x6c, 0x0d, 0x7a, 0xde, 0xc2, 0x46, 0x37, 0x61, 0x9b, 0x08, 0xc1, 0x42,
	0x7b, 0x0b, 0x5b, 0x83, 0x1b, 0x5e, 0x61, 0x38, 0x3f, 0x5b, 0x30, 0x78, 0x75, 0x76, 0x25, 0x78,
	0xaa, 0x28, 0xba, 0x07, 0x7b, 0x59, 0xee, 0xf7, 0xb5, 0x59, 0xc8, 0x4b, 0x5c, 0xf7, 0x76, 0xb3,
	0x65, 0xac, 0x41, 0x10, 0xf3, 0x80, 0x68, 0xc6, 0xd3, 0xbc, 0x50, 0xcf, 0x5b, 0xd8, 0xe8, 0x36,
	0x80, 0xe4, 0x99, 0x66, 0x69, 0xe4, 0xb3, 0xd0, 0xbe, 0x96, 0x6f, 0xee, 0x95, 0x9e, 0x51, 0xe8,
	0xfc, 0x08, 0xf7, 0x1a, 0x48, 0x86, 0x2c, 0x65, 0xea, 0x45, 0x01, 0x64, 0x71, 0xc2, 0x16, 0x10,
	0x9a, 0x65, 0xb6, 0x56, 0xca, 0xa0, 0x7d, 0xd8, 0x21, 0x42, 0x54, 0x08, 0x0a, 0x22, 0x46, 0xa1,
	0xf3, 0xcd, 0x0a, 0x0f, 0xf5, 0xea, 0x8f, 0xbf, 0x7c, 0xca, 0xa2, 0x1a, 0x0f, 0xef, 0xc3, 0x4d,
	0xc5, 0xa2, 0x94, 0x86, 0x3e, 0x4b, 0x95, 0x26, 0x71, 0x5c, 0xf4, 0xb7, 0xa4, 0xfc, 0xf5, 0x62,
	0x6d, 0x54, 0x5f, 0x72, 0xfe, 0xb6, 0xe0, 0xfe, 0xda, 0xfc, 0x9f, 0xd1, 0x88, 0x04, 0xd3, 0x73,
	0xef, 0xc9, 0x95, 0x1f, 0xd3, 0x4c, 0xc1, 0x24, 0x26, 0x91, 0xb2, 0xaf, 0x17, 0xde, 0xdc, 0x40,
	0x6f, 0x42, 0x4f, 0x73, 0x1e, 0xfb, 0xf9, 0xe0, 0x6c, 0x17, 0x6d, 0x33, 0x8e, 0x0b, 0x92, 0x50,
	0x67, 0x08, 0x47, 0xad, 0x90, 0x97, 0xe4, 0xbc, 0x01, 0x1d, 0x33, 0x73, 0xa6, 0x72, 0xc1, 0xc7,
	0x8e, 0x31, 0x47, 0xa1, 0x73, 0x08, 0xce, 0xa6, 0xfe, 0x16, 0xdb, 0x9d, 0x07, 0x70, 0xb0, 0x1a,
	0x15, 0x9e, 0x7b, 0x4f, 0x8a, 0xb0, 0xc5, 0x78, 0xd6, 0x8e, 0x67, 0x8a, 0x6c, 0x57, 0x5d, 0xfc,
	0x69, 0x0b, 0xee, 0x34, 0xb6, 0x3f, 0x7c, 0xc9, 0x94, 0x61, 0x64, 0x91, 0x62, 0x2d, 0xbe, 0x5a,
	0xca, 0xad, 0x3a, 0x63, 0xb7, 0xa0, 0x4b, 0x02, 0xcd, 0x65, 0x45, 0xe5, 0xb6, 0xd7, 0xc9, 0xed,
	0x51, 0x88, 0x0e, 0xe0, 0x86, 0xca, 0x84, 0x88, 0xcd, 0xe5, 0xad, 0x51, 0xb7, 0x57, 0x39, 0x2f,
	0xca, 0x7b, 0x57, 0x30, 0xbe, 0x53, 0x67, 0xfc, 0x16, 0x74, 0x13, 0x1e, 0xfa, 0x7a, 0x2a, 0xa8,
	0xdd, 0xc9, 0x77, 0x75, 0x12, 0x1e, 0x3e, 0x9b, 0x0a, 0x8a, 0xde, 0x82, 0x9e, 0x66, 0x09, 0x55,
	0x9a, 0x24, 0xc2, 0xee, 0x62, 0x6b, 0xd0, 0xf1, 0x96, 0x0e, 0x84, 0x61, 0x8f, 0x4b, 0x16, 0xf9,
	0xd5, 0x19, 0x7a, 0xf9, 0x66, 0x30, 0xbe, 0x61, 0xc1, 0x33, 0x81, 0xc3, 0xcd, 0x0c, 0x96, 0x8d,
	0xfa, 0x08, 0x3a, 0xc5, 0x3c, 0x29, 0xdb, 0xc2, 0xd7, 0x06, 0xbb, 0xa7, 0x77, 0xdd, 0xcd, 0xd4,
	0x79, 0x55, 0xbc, 0xf3, 0x39, 0xdc, 0x6e, 0x84, 0x9e, 0xf3, 0x1f, 0xd2, 0xc6, 0x35, 0x6d, 0x49,
	0xf2, 0xa2, 0x6f, 0x5f, 0xad, 0xb4, 0xad, 0x96, 0x70, 0xa9, 0x3d, 0x61, 0xe5, 0xcc, 0x64, 0x5c,
	0xa6, 0xdd, 0xad, 0x7c, 0xcf, 0x65, 0xbc, 0x26, 0xf7, 0xe9, 0x1f, 0x00, 0xbb, 0xb5, 0xdc, 0xe8,
	0x2f, 0x0b, 0xec, 0x12, 0x67, 0x71, 0xb1, 0x6b, 0x5a, 0x87, 0x06, 0x6e, 0x4b, 0xad, 0xed, 0xbf,
	0xeb, 0xb6, 0xd5, 0x4d, 0xe7, 0xe3, 0xd9, 0xdc, 0x7e, 0x50, 0x06, 0xe0, 0x82, 0x43, 0x9c, 0xdf,
	0x6b, 0x3c, 0xe1, 0x12, 0x37, 0x34, 0x04, 0x1b, 0x9e, 0xaa, 0x98, 0x13, 0x6c, 0xa4, 0x84, 0xa5,
	0x11, 0xfa, 0xd3, 0x82, 0xfd, 0x32, 0xc1, 0xa2, 0x1d, 0xff, 0x1b, 0x60, 0xfa, 0x92, 0x06, 0x99,
	0x26, 0xe3, 0x98, 0xae, 0xa0, 0x15, 0x92, 0x07, 0x54, 0x29, 0x03, 0x78, 0xbe, 0x04, 0x7c, 0xf6,
	0xf0, 0xd1, 0x95, 0x03, 0x7e, 0x34, 0x9b, 0xdb, 0x67, 0x6b, 0x01, 0x07, 0x99, 0xd2, 0x3c, 0x69,
	0x85, 0xfb, 0x77, 0x0b, 0xd0, 0x65, 0xe9, 0x47, 0x8e, 0xfb, 0xca, 0xa7, 0x69, 0x15, 0xee, 0x86,
	0x07, 0xc4, 0x19, 0xce, 0xe6, 0xf6, 0xa7, 0x67, 0x3c, 0x49, 0x98, 0xc6, 0x09, 0xd5, 0x2f, 0xb8,
	0x41, 0x9b, 0x37, 0x1b, 0x93, 0x74, 0x65, 0x20, 0xc8, 0x44, 0x53, 0x69, 0xdc, 0x25, 0x5c, 0xa6,
	0x70, 0xc0, 0x13, 0x11, 0x53, 0x4d, 0xd1, 0x6f, 0x16, 0xec, 0xd7, 0xeb, 0x2c, 0x55, 0xee, 0xc8,
	0x6d, 0xff, 0xda, 0xf4, 0x8f, 0xdd, 0xff, 0x20, 0xf0, 0xce, 0x7b, 0xb3, 0xb9, 0x7d, 0xdc, 0x04,
	0xff, 0x6f, 0x53, 0x51, 0x23, 0xf5, 0xd7, 0x15, 0x98, 0x8b, 0x89, 0x68, 0xc5, 0xeb, 0x81, 0xdb,
	0xe2, 0xd9, 0xf8, 0x70, 0x36, 0xb7, 0x3f, 0xb8, 0x0c, 0x6a, 0x4d, 0xe7, 0x6b, 0xd8, 0x7e, 0xb1,
	0xe0, 0xb5, 0xa6, 0x42, 0xa2, 0x43, 0xb7, 0xc5, 0x0b, 0xd4, 0x7f, 0xdb, 0x6d, 0xa3, 0xb2, 0x8e,
	0x3b, 0x9b, 0xdb, 0xf7, 0xcd, 0xa2, 0xc2, 0x17, 0x38, 0xe1, 0x4a, 0x63, 0x49, 0x03, 0x9a, 0x6a,
	0x2c, 0x24, 0xe3, 0xb2, 0x6c, 0xaa, 0xc2, 0xe3, 0x29, 0xce, 0x3f, 0x64, 0xe8, 0x31, 0x74, 0x2b,
	0xf1, 0x43, 0x77, 0xdc, 0x8d, 0x2a, 0xdb, 0xbf, 0xeb, 0x6e, 0x16, 0xcd, 0xfe, 0xe9, 0x6c, 0x6e,
	0xbb, 0x4f, 0xa9, 0xfc, 0x9e, 0x05, 0xb4, 0xa4, 0x45, 0xe5, 0xbc, 0x10, 0x21, 0x70, 0x42, 0x52,
	0x12, 0xd1, 0xc4, 0x60, 0x19, 0x4f, 0x71, 0xf9, 0xa7, 0x55, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xb2, 0x30, 0x27, 0x72, 0xec, 0x0a, 0x00, 0x00,
}
